// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountPermissions = `-- name: AccountPermissions :many
SELECT DISTINCT rp.permission
FROM identity.account_roles ar
JOIN identity.role_permissions rp ON rp.role_id = ar.role_id
WHERE ar.account_id = $1
ORDER BY rp.permission
`

func (q *Queries) AccountPermissions(ctx context.Context, accountID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, accountPermissions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountRoleIDs = `-- name: AccountRoleIDs :many
SELECT role_id FROM identity.account_roles WHERE account_id = $1
`

func (q *Queries) AccountRoleIDs(ctx context.Context, accountID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, accountRoleIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM identity.accounts
WHERE ($1::text IS NULL
       OR name ILIKE '%' || $1::text || '%'
       OR email ILIKE '%' || $1::text || '%')
  AND ($2::boolean IS NULL OR active = $2::boolean)
  AND ($3::text IS NULL OR (CASE WHEN NOT active THEN 'disabled' WHEN password_hash IS NULL THEN 'invited' ELSE 'active' END) = $3::text)
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM identity.account_roles ar
        WHERE ar.account_id = accounts.id AND ar.role_id = $4::uuid))
`

type CountAccountsParams struct {
	Q      *string
	Active *bool
	Status *string
	RoleID *uuid.UUID
}

func (q *Queries) CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts,
		arg.Q,
		arg.Active,
		arg.Status,
		arg.RoleID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccountsByStatus = `-- name: CountAccountsByStatus :many
SELECT (CASE WHEN NOT active THEN 'disabled' WHEN password_hash IS NULL THEN 'invited' ELSE 'active' END)::text AS status, count(*)::bigint AS n
FROM identity.accounts
WHERE ($1::text IS NULL
       OR name ILIKE '%' || $1::text || '%'
       OR email ILIKE '%' || $1::text || '%')
  AND ($2::uuid IS NULL OR EXISTS (
        SELECT 1 FROM identity.account_roles ar
        WHERE ar.account_id = accounts.id AND ar.role_id = $2::uuid))
GROUP BY 1
`

type CountAccountsByStatusParams struct {
	Q      *string
	RoleID *uuid.UUID
}

type CountAccountsByStatusRow struct {
	Status string
	N      int64
}

// Số account theo trạng thái với cùng tìm kiếm và lọc role, bỏ qua lọc trạng thái
// (đếm cho các nút lọc)
// trạng thái suy ra như domain.Account.Status
func (q *Queries) CountAccountsByStatus(ctx context.Context, arg CountAccountsByStatusParams) ([]CountAccountsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAccountsByStatus, arg.Q, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAccountsByStatusRow{}
	for rows.Next() {
		var i CountAccountsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveAccountsWithRole = `-- name: CountActiveAccountsWithRole :one
SELECT count(*) FROM identity.accounts a
JOIN identity.account_roles ar ON ar.account_id = a.id
WHERE ar.role_id = $1 AND a.active
`

func (q *Queries) CountActiveAccountsWithRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAccountsWithRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllAccounts = `-- name: CountAllAccounts :one
SELECT count(*) FROM identity.accounts
`

func (q *Queries) CountAllAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO identity.accounts (id, email, name, password_hash, member_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, password_hash, member_id, active, version, created_at, updated_at
`

type CreateAccountParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash *string
	MemberID     *uuid.UUID
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.MemberID,
	)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.MemberID,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountRoles = `-- name: DeleteAccountRoles :exec
DELETE FROM identity.account_roles WHERE account_id = $1
`

func (q *Queries) DeleteAccountRoles(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountRoles, accountID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, email, name, password_hash, member_id, active, version, created_at, updated_at FROM identity.accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.MemberID,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, name, password_hash, member_id, active, version, created_at, updated_at FROM identity.accounts WHERE lower(email) = lower($1)
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.MemberID,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, email, name, password_hash, member_id, active, version, created_at, updated_at FROM identity.accounts WHERE id = $1 FOR NO KEY UPDATE
`

// Khoá hàng để đổi trạng thái/mật khẩu/role không chen nhau. NO KEY UPDATE:
// không bao giờ đổi khoá chính, nên không chặn insert tham chiếu account (FK
// lấy KEY SHARE), vd đăng nhập tạo refresh_families
func (q *Queries) GetAccountForUpdate(ctx context.Context, id uuid.UUID) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.MemberID,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByIDs = `-- name: GetAccountsByIDs :many
SELECT id, email, name, password_hash, member_id, active, version, created_at, updated_at FROM identity.accounts WHERE id = ANY($1::uuid[]) ORDER BY name, id
`

func (q *Queries) GetAccountsByIDs(ctx context.Context, ids []uuid.UUID) ([]IdentityAccount, error) {
	rows, err := q.db.Query(ctx, getAccountsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAccount{}
	for rows.Next() {
		var i IdentityAccount
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.MemberID,
			&i.Active,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccountRole = `-- name: InsertAccountRole :exec
INSERT INTO identity.account_roles (account_id, role_id) VALUES ($1, $2)
`

type InsertAccountRoleParams struct {
	AccountID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) InsertAccountRole(ctx context.Context, arg InsertAccountRoleParams) error {
	_, err := q.db.Exec(ctx, insertAccountRole, arg.AccountID, arg.RoleID)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, email, name, password_hash, member_id, active, version, created_at, updated_at FROM identity.accounts
WHERE ($1::text IS NULL
       OR name ILIKE '%' || $1::text || '%'
       OR email ILIKE '%' || $1::text || '%')
  AND ($2::boolean IS NULL OR active = $2::boolean)
  AND ($3::text IS NULL OR (CASE WHEN NOT active THEN 'disabled' WHEN password_hash IS NULL THEN 'invited' ELSE 'active' END) = $3::text)
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM identity.account_roles ar
        WHERE ar.account_id = accounts.id AND ar.role_id = $4::uuid))
ORDER BY name, id
LIMIT $6 OFFSET $5
`

type ListAccountsParams struct {
	Q      *string
	Active *bool
	Status *string
	RoleID *uuid.UUID
	Off    int32
	Lim    int32
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]IdentityAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.Q,
		arg.Active,
		arg.Status,
		arg.RoleID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAccount{}
	for rows.Next() {
		var i IdentityAccount
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.MemberID,
			&i.Active,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInviteExpiries = `-- name: ListInviteExpiries :many
SELECT account_id, expires_at FROM identity.password_tokens
WHERE purpose = 'invite' AND account_id = ANY($1::uuid[])
`

type ListInviteExpiriesRow struct {
	AccountID uuid.UUID
	ExpiresAt time.Time
}

// Hạn link mời còn hiệu lực của nhiều account
func (q *Queries) ListInviteExpiries(ctx context.Context, ids []uuid.UUID) ([]ListInviteExpiriesRow, error) {
	rows, err := q.db.Query(ctx, listInviteExpiries, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInviteExpiriesRow{}
	for rows.Next() {
		var i ListInviteExpiriesRow
		if err := rows.Scan(&i.AccountID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastSignIns = `-- name: ListLastSignIns :many
SELECT account_id, last_at FROM identity.account_sign_ins WHERE account_id = ANY($1::uuid[])
`

func (q *Queries) ListLastSignIns(ctx context.Context, ids []uuid.UUID) ([]IdentityAccountSignIn, error) {
	rows, err := q.db.Query(ctx, listLastSignIns, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAccountSignIn{}
	for rows.Next() {
		var i IdentityAccountSignIn
		if err := rows.Scan(&i.AccountID, &i.LastAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesOfAccounts = `-- name: ListRolesOfAccounts :many
SELECT ar.account_id, r.id, r.name
FROM identity.account_roles ar
JOIN identity.roles r ON r.id = ar.role_id
WHERE ar.account_id = ANY($1::uuid[])
ORDER BY ar.account_id, r.name, r.id
`

type ListRolesOfAccountsRow struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	Name      string
}

// Role của nhiều account một lần (danh sách account)
func (q *Queries) ListRolesOfAccounts(ctx context.Context, ids []uuid.UUID) ([]ListRolesOfAccountsRow, error) {
	rows, err := q.db.Query(ctx, listRolesOfAccounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesOfAccountsRow{}
	for rows.Next() {
		var i ListRolesOfAccountsRow
		if err := rows.Scan(&i.AccountID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRole = `-- name: LockRole :one
SELECT id FROM identity.roles WHERE id = $1 FOR NO KEY UPDATE
`

// Khoá hàng role Administrator: mọi thao tác có thể làm mất một admin (khoá
// account, đổi role) chạy lần lượt, để kiểm tra "còn admin" không bị hai
// transaction cùng lọt. Luôn khoá trước hàng account.
func (q *Queries) LockRole(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockRole, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const recordSignIn = `-- name: RecordSignIn :exec
INSERT INTO identity.account_sign_ins (account_id, last_at) VALUES ($1, now())
ON CONFLICT (account_id) DO UPDATE SET last_at = excluded.last_at
`

func (q *Queries) RecordSignIn(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordSignIn, accountID)
	return err
}

const setAccountActive = `-- name: SetAccountActive :one
UPDATE identity.accounts
SET active = $1, version = version + 1, updated_at = now()
WHERE id = $2
RETURNING id, email, name, password_hash, member_id, active, version, created_at, updated_at
`

type SetAccountActiveParams struct {
	Active bool
	ID     uuid.UUID
}

func (q *Queries) SetAccountActive(ctx context.Context, arg SetAccountActiveParams) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, setAccountActive, arg.Active, arg.ID)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.MemberID,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAccountPassword = `-- name: SetAccountPassword :exec
UPDATE identity.accounts SET password_hash = $1, updated_at = now() WHERE id = $2
`

type SetAccountPasswordParams struct {
	PasswordHash *string
	ID           uuid.UUID
}

func (q *Queries) SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, setAccountPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE identity.accounts
SET name = $1, member_id = $2, version = version + 1, updated_at = now()
WHERE id = $3 AND version = $4
RETURNING id, email, name, password_hash, member_id, active, version, created_at, updated_at
`

type UpdateAccountProfileParams struct {
	Name     string
	MemberID *uuid.UUID
	ID       uuid.UUID
	Version  int32
}

// Optimistic locking: 0 hàng nghĩa là version đã đổi (hoặc không có account)
func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile,
		arg.Name,
		arg.MemberID,
		arg.ID,
		arg.Version,
	)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.MemberID,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
