// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type IdentityAccount struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	MemberID     *uuid.UUID
	Active       bool
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type IdentityAccountRole struct {
	AccountID uuid.UUID
	RoleID    uuid.UUID
}

type IdentityPermission struct {
	Code        string
	Description string
}

type IdentityRefreshFamily struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	UserAgent         string
	Ip                string
	CreatedAt         time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         *time.Time
	RevokedReason     *string
}

type IdentityRefreshToken struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ParentID  *uuid.UUID
	IssuedAt  time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type IdentityRole struct {
	ID          uuid.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type IdentityRolePermission struct {
	RoleID     uuid.UUID
	Permission string
}

type PlatformEvent struct {
	ID            uuid.UUID
	Type          string
	AggregateType string
	AggregateID   uuid.UUID
	ActorID       *uuid.UUID
	OccurredAt    time.Time
	Payload       json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
