// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePasswordToken = `-- name: ConsumePasswordToken :one
DELETE FROM identity.password_tokens WHERE token_hash = $1 RETURNING account_id, purpose, id, token_hash, created_at, expires_at
`

// Dùng token: xoá rồi mới kiểm tra, nên hai lần gửi cùng lúc chỉ một bên thấy hàng
func (q *Queries) ConsumePasswordToken(ctx context.Context, tokenHash []byte) (IdentityPasswordToken, error) {
	row := q.db.QueryRow(ctx, consumePasswordToken, tokenHash)
	var i IdentityPasswordToken
	err := row.Scan(
		&i.AccountID,
		&i.Purpose,
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAccountPasswordTokens = `-- name: DeleteAccountPasswordTokens :exec
DELETE FROM identity.password_tokens WHERE account_id = $1
`

func (q *Queries) DeleteAccountPasswordTokens(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountPasswordTokens, accountID)
	return err
}

const deleteExpiredPasswordTokens = `-- name: DeleteExpiredPasswordTokens :execrows
DELETE FROM identity.password_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredPasswordTokens(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordTokens, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountPasswordToken = `-- name: GetAccountPasswordToken :one
SELECT account_id, purpose, id, token_hash, created_at, expires_at FROM identity.password_tokens WHERE account_id = $1 AND purpose = $2
`

type GetAccountPasswordTokenParams struct {
	AccountID uuid.UUID
	Purpose   string
}

func (q *Queries) GetAccountPasswordToken(ctx context.Context, arg GetAccountPasswordTokenParams) (IdentityPasswordToken, error) {
	row := q.db.QueryRow(ctx, getAccountPasswordToken, arg.AccountID, arg.Purpose)
	var i IdentityPasswordToken
	err := row.Scan(
		&i.AccountID,
		&i.Purpose,
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPasswordToken = `-- name: GetPasswordToken :one
SELECT account_id, purpose, id, token_hash, created_at, expires_at FROM identity.password_tokens WHERE id = $1
`

func (q *Queries) GetPasswordToken(ctx context.Context, id uuid.UUID) (IdentityPasswordToken, error) {
	row := q.db.QueryRow(ctx, getPasswordToken, id)
	var i IdentityPasswordToken
	err := row.Scan(
		&i.AccountID,
		&i.Purpose,
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertPasswordToken = `-- name: UpsertPasswordToken :one
INSERT INTO identity.password_tokens (account_id, purpose, id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, purpose) DO UPDATE
SET id = EXCLUDED.id, token_hash = EXCLUDED.token_hash, created_at = now(), expires_at = EXCLUDED.expires_at
RETURNING account_id, purpose, id, token_hash, created_at, expires_at
`

type UpsertPasswordTokenParams struct {
	AccountID uuid.UUID
	Purpose   string
	ID        uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

// Phát token: ghi đè token cùng loại của account (link cũ chết ngay)
func (q *Queries) UpsertPasswordToken(ctx context.Context, arg UpsertPasswordTokenParams) (IdentityPasswordToken, error) {
	row := q.db.QueryRow(ctx, upsertPasswordToken,
		arg.AccountID,
		arg.Purpose,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i IdentityPasswordToken
	err := row.Scan(
		&i.AccountID,
		&i.Purpose,
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
