// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveMembersByRole = `-- name: CountActiveMembersByRole :many
SELECT ar.role_id, count(*)::bigint AS n
FROM identity.account_roles ar
JOIN identity.accounts a ON a.id = ar.account_id
WHERE a.active
GROUP BY ar.role_id
`

type CountActiveMembersByRoleRow struct {
	RoleID uuid.UUID
	N      int64
}

// Số account chưa bị khoá (kể cả đang được mời) giữ mỗi role (trang vai trò)
func (q *Queries) CountActiveMembersByRole(ctx context.Context) ([]CountActiveMembersByRoleRow, error) {
	rows, err := q.db.Query(ctx, countActiveMembersByRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveMembersByRoleRow{}
	for rows.Next() {
		var i CountActiveMembersByRoleRow
		if err := rows.Scan(&i.RoleID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRoleAssignments = `-- name: CountRoleAssignments :one
SELECT count(*) FROM identity.account_roles WHERE role_id = $1
`

func (q *Queries) CountRoleAssignments(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleAssignments, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO identity.roles (id, name, description) VALUES ($1, $2, $3)
RETURNING id, name, description, is_system, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ID, arg.Name, arg.Description)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
UPDATE identity.roles SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM identity.account_roles WHERE role_id = $1)
`

// Xoá mềm; không xoá nếu còn account giữ role (service đã kiểm tra, đây là lớp chặn cuối)
func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM identity.role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleAnyForUpdate = `-- name: GetRoleAnyForUpdate :one
SELECT id, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles WHERE id = $1 FOR UPDATE
`

// Kể cả role đã xoá (khôi phục)
func (q *Queries) GetRoleAnyForUpdate(ctx context.Context, id uuid.UUID) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleAnyForUpdate, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT id, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) GetRolesByIDs(ctx context.Context, ids []uuid.UUID) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO identity.role_permissions (role_id, permission) VALUES ($1, $2)
`

type InsertRolePermissionParams struct {
	RoleID     uuid.UUID
	Permission string
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.Permission)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT code, description FROM identity.permissions ORDER BY code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]IdentityPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityPermission{}
	for rows.Next() {
		var i IdentityPermission
		if err := rows.Scan(&i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles WHERE deleted_at IS NULL ORDER BY name
`

// Role đã xoá (xoá mềm) không hiện ở đâu, trừ khi khôi phục
func (q *Queries) ListRoles(ctx context.Context) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveRole = `-- name: LockActiveRole :one
SELECT id, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

// Khoá role trước khi xoá mềm: đợi các lần gán chưa commit (khoá ngoại giữ FOR KEY SHARE)
func (q *Queries) LockActiveRole(ctx context.Context, id uuid.UUID) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, lockActiveRole, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockActiveRolesByIDs = `-- name: LockActiveRolesByIDs :many
SELECT id, name, description, is_system, created_at, updated_at, deleted_at FROM identity.roles WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL ORDER BY id FOR SHARE
`

// Khoá chia sẻ các role sắp gán: xoá role cùng lúc phải đợi, và role vừa bị xoá thì
// không còn trong kết quả (điều kiện được xét lại sau khi đợi). Khoá theo id để không deadlock
func (q *Queries) LockActiveRolesByIDs(ctx context.Context, ids []uuid.UUID) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, lockActiveRolesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreRole = `-- name: RestoreRole :one
UPDATE identity.roles SET deleted_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_system, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreRole(ctx context.Context, id uuid.UUID) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, restoreRole, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const rolePermissions = `-- name: RolePermissions :many
SELECT permission FROM identity.role_permissions WHERE role_id = $1 ORDER BY permission
`

func (q *Queries) RolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, rolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolesPermissions = `-- name: RolesPermissions :many
SELECT role_id, permission FROM identity.role_permissions
WHERE role_id = ANY($1::uuid[])
ORDER BY role_id, permission
`

// Quyền của nhiều role một lần, để dựng danh sách role không N+1
func (q *Queries) RolesPermissions(ctx context.Context, roleIds []uuid.UUID) ([]IdentityRolePermission, error) {
	rows, err := q.db.Query(ctx, rolesPermissions, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRolePermission{}
	for rows.Next() {
		var i IdentityRolePermission
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRole = `-- name: TouchRole :exec
UPDATE identity.roles SET updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TouchRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRole, id)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE identity.roles SET name = $1, description = $2, updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, description, is_system, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	Name        string
	Description string
	ID          uuid.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
