// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countRoleAssignments = `-- name: CountRoleAssignments :one
SELECT count(*) FROM identity.account_roles WHERE role_id = $1
`

func (q *Queries) CountRoleAssignments(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleAssignments, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO identity.roles (id, name, description) VALUES ($1, $2, $3)
RETURNING id, name, description, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ID, arg.Name, arg.Description)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM identity.roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM identity.role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, name, description, is_system, created_at, updated_at FROM identity.roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT id, name, description, is_system, created_at, updated_at FROM identity.roles WHERE id = ANY($1::uuid[]) ORDER BY name
`

func (q *Queries) GetRolesByIDs(ctx context.Context, ids []uuid.UUID) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO identity.role_permissions (role_id, permission) VALUES ($1, $2)
`

type InsertRolePermissionParams struct {
	RoleID     uuid.UUID
	Permission string
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.Permission)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT code, description FROM identity.permissions ORDER BY code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]IdentityPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityPermission{}
	for rows.Next() {
		var i IdentityPermission
		if err := rows.Scan(&i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_system, created_at, updated_at FROM identity.roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolePermissions = `-- name: RolePermissions :many
SELECT permission FROM identity.role_permissions WHERE role_id = $1 ORDER BY permission
`

func (q *Queries) RolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, rolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolesPermissions = `-- name: RolesPermissions :many
SELECT role_id, permission FROM identity.role_permissions
WHERE role_id = ANY($1::uuid[])
ORDER BY role_id, permission
`

// Quyền của nhiều role một lần, để dựng danh sách role không N+1
func (q *Queries) RolesPermissions(ctx context.Context, roleIds []uuid.UUID) ([]IdentityRolePermission, error) {
	rows, err := q.db.Query(ctx, rolesPermissions, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityRolePermission{}
	for rows.Next() {
		var i IdentityRolePermission
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRole = `-- name: TouchRole :exec
UPDATE identity.roles SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRole, id)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE identity.roles SET name = $1, description = $2, updated_at = now()
WHERE id = $3
RETURNING id, name, description, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	Name        string
	Description string
	ID          uuid.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
