// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFamily = `-- name: CreateFamily :exec
INSERT INTO identity.refresh_families (id, account_id, user_agent, ip, absolute_expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateFamilyParams struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	UserAgent         string
	Ip                string
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) error {
	_, err := q.db.Exec(ctx, createFamily,
		arg.ID,
		arg.AccountID,
		arg.UserAgent,
		arg.Ip,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO identity.refresh_tokens (id, family_id, token_hash, parent_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ParentID  *uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ParentID,
		arg.ExpiresAt,
	)
	return err
}

const deleteDeadFamilies = `-- name: DeleteDeadFamilies :execrows
DELETE FROM identity.refresh_families
WHERE GREATEST(revoked_at, absolute_expires_at) < $1::timestamptz
`

// Dọn rác: family đã chết (thu hồi hoặc hết hạn tuyệt đối) quá retention
func (q *Queries) DeleteDeadFamilies(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeadFamilies, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUsedTokens = `-- name: DeleteUsedTokens :execrows
DELETE FROM identity.refresh_tokens
WHERE used_at IS NOT NULL AND expires_at < $1::timestamptz
`

// Token đã dùng trong family còn sống, hết hạn quá retention. Không đụng ngọn.
func (q *Queries) DeleteUsedTokens(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUsedTokens, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const familyOfToken = `-- name: FamilyOfToken :one
SELECT family_id FROM identity.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) FamilyOfToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, familyOfToken, tokenHash)
	var family_id uuid.UUID
	err := row.Scan(&family_id)
	return family_id, err
}

const getFamilyTip = `-- name: GetFamilyTip :one
SELECT id FROM identity.refresh_tokens WHERE family_id = $1 AND used_at IS NULL
`

// Ngọn của family: token chưa dùng duy nhất (refresh_tokens_live đảm bảo)
func (q *Queries) GetFamilyTip(ctx context.Context, familyID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFamilyTip, familyID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRefreshForUpdate = `-- name: GetRefreshForUpdate :one
SELECT
  t.id                  AS token_id,
  t.family_id           AS family_id,
  t.used_at             AS used_at,
  t.expires_at          AS expires_at,
  f.account_id          AS account_id,
  f.revoked_at          AS revoked_at,
  f.absolute_expires_at AS absolute_expires_at,
  a.active              AS account_active
FROM identity.refresh_tokens t
JOIN identity.refresh_families f ON f.id = t.family_id
JOIN identity.accounts a ON a.id = f.account_id
WHERE t.token_hash = $1
FOR UPDATE OF t, f
`

type GetRefreshForUpdateRow struct {
	TokenID           uuid.UUID
	FamilyID          uuid.UUID
	UsedAt            *time.Time
	ExpiresAt         time.Time
	AccountID         uuid.UUID
	RevokedAt         *time.Time
	AbsoluteExpiresAt time.Time
	AccountActive     bool
}

// Trái tim của vòng xoay (port từ mimir). Khoá cả hàng token lẫn hàng family:
// hai lần refresh song song trên cùng family phải xếp hàng, để lần đến sau đọc
// được used_at mới nhất và rẽ vào nhánh ân hạn thay vì chẻ family. Kèm trạng
// thái account để account bị khoá không refresh được.
func (q *Queries) GetRefreshForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshForUpdate, tokenHash)
	var i GetRefreshForUpdateRow
	err := row.Scan(
		&i.TokenID,
		&i.FamilyID,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.AccountID,
		&i.RevokedAt,
		&i.AbsoluteExpiresAt,
		&i.AccountActive,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE identity.refresh_tokens SET used_at = $1 WHERE id = $2 AND used_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	UsedAt *time.Time
	ID     uuid.UUID
}

// Guard used_at IS NULL: 0 hàng là có ai đó đánh dấu trước
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccountFamilies = `-- name: RevokeAccountFamilies :execrows
UPDATE identity.refresh_families
SET revoked_at = now(), revoked_reason = $1
WHERE account_id = $2 AND revoked_at IS NULL
  AND ($3::uuid IS NULL OR id <> $3::uuid)
`

type RevokeAccountFamiliesParams struct {
	Reason    *string
	AccountID uuid.UUID
	Keep      *uuid.UUID
}

// Thu hồi mọi phiên còn sống của account, trừ family đang dùng (nếu có)
func (q *Queries) RevokeAccountFamilies(ctx context.Context, arg RevokeAccountFamiliesParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccountFamilies, arg.Reason, arg.AccountID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE identity.refresh_families
SET revoked_at = now(), revoked_reason = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeFamilyParams struct {
	Reason *string
	ID     uuid.UUID
}

func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeFamily, arg.Reason, arg.ID)
	return err
}
