// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getEvent = `-- name: GetEvent :one
SELECT id, type, aggregate_type, aggregate_id, actor_id, occurred_at, payload
FROM platform.events
WHERE id = $1
`

type GetEventRow struct {
	ID            uuid.UUID
	Type          string
	AggregateType string
	AggregateID   uuid.UUID
	ActorID       *uuid.UUID
	OccurredAt    time.Time
	Payload       json.RawMessage
}

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AggregateType,
		&i.AggregateID,
		&i.ActorID,
		&i.OccurredAt,
		&i.Payload,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO platform.events (id, type, aggregate_type, aggregate_id, actor_id, occurred_at, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID            uuid.UUID
	Type          string
	AggregateType string
	AggregateID   uuid.UUID
	ActorID       *uuid.UUID
	OccurredAt    time.Time
	Payload       json.RawMessage
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.Type,
		arg.AggregateType,
		arg.AggregateID,
		arg.ActorID,
		arg.OccurredAt,
		arg.Payload,
	)
	return err
}
