// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityAccount struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash *string
	MemberID     *uuid.UUID
	Active       bool
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type IdentityAccountRole struct {
	AccountID uuid.UUID
	RoleID    uuid.UUID
}

type IdentityAccountSignIn struct {
	AccountID uuid.UUID
	LastAt    time.Time
}

type IdentityPasswordToken struct {
	AccountID uuid.UUID
	Purpose   string
	ID        uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

type IdentityPermission struct {
	Code        string
	Description string
}

type IdentityRefreshFamily struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	UserAgent         string
	Ip                string
	CreatedAt         time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         *time.Time
	RevokedReason     *string
}

type IdentityRefreshToken struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ParentID  *uuid.UUID
	IssuedAt  time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type IdentityRole struct {
	ID          uuid.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type IdentityRolePermission struct {
	RoleID     uuid.UUID
	Permission string
}

type InventoryAsset struct {
	ID             uuid.UUID
	Tag            string
	Name           string
	Description    string
	AssetTypeID    uuid.UUID
	StatusID       uuid.UUID
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	PurchaseDate   pgtype.Date
	RetiredAt      *time.Time
	RetiredReason  *string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type InventoryAssetAttributeOption struct {
	ID          uuid.UUID
	AttributeID uuid.UUID
	DataType    string
	Label       string
	Position    int32
	RemovedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type InventoryAssetAttributeValue struct {
	AssetID       uuid.UUID
	AttributeID   uuid.UUID
	AssetTypeID   uuid.UUID
	DataType      string
	ValueText     *string
	ValueNumber   pgtype.Numeric
	ValueDate     pgtype.Date
	ValueBool     *bool
	ValueOptionID *uuid.UUID
}

type InventoryAssetStatus struct {
	ID         uuid.UUID
	Name       string
	Kind       string
	IsDefault  bool
	IsSystem   bool
	Position   int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type InventoryAssetType struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Description string
	IsSystem    bool
	ArchivedAt  *time.Time
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type InventoryAssetTypeAttribute struct {
	ID          uuid.UUID
	AssetTypeID uuid.UUID
	Key         string
	Label       string
	DataType    string
	Unit        *string
	IsRequired  bool
	Position    int32
	RemovedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type InventoryExportProfile struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Shared    bool
	Layout    json.RawMessage
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type PlatformEvent struct {
	ID            uuid.UUID
	Type          string
	AggregateType string
	AggregateID   uuid.UUID
	ActorID       *uuid.UUID
	OccurredAt    time.Time
	Payload       json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
