// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type PlatformEvent struct {
	ID            uuid.UUID
	Type          string
	AggregateType string
	AggregateID   uuid.UUID
	ActorID       *uuid.UUID
	OccurredAt    time.Time
	Payload       json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
