// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetEvent(ctx context.Context, id uuid.UUID) (GetEventRow, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
}

var _ Querier = (*Queries)(nil)
