/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh cookie and get a new access token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out this device */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change your own password; signs out your other devices */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a password reset link (always 202, whether or not the email has an account) */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a password with the token from an invitation or reset email */
        post: operations["setPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in account with its roles and permissions */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change your own display name (any signed-in account) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts (identity.account.read) */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account (identity.account.manage) */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        /** Get an account with its roles (identity.account.read) */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update name or member link (identity.account.manage) */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/accounts/{accountID}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable an account and sign out all its devices (identity.account.manage) */
        post: operations["disableAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountID}/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign an account out of every device (identity.account.manage) */
        post: operations["signOutAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountID}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable a disabled account (identity.account.manage) */
        post: operations["enableAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountID}/invitation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a new invitation link; the previous one stops working (identity.account.manage) */
        post: operations["resendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountID}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a password reset link, or a new invitation if the account has no password yet (identity.account.manage) */
        post: operations["sendPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountID}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the account's roles (identity.account.manage) */
        put: operations["assignRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles with their permissions (identity.role.read) */
        get: operations["listRoles"];
        put?: never;
        /** Create a role (identity.role.manage) */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleID: components["parameters"]["RoleID"];
            };
            cookie?: never;
        };
        /** Get a role (identity.role.read) */
        get: operations["getRole"];
        put?: never;
        post?: never;
        /** Delete an unassigned custom role (identity.role.manage) */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /** Rename or describe a role; system roles cannot be renamed (identity.role.manage) */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/roles/{roleID}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleID: components["parameters"]["RoleID"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the role's permissions (identity.role.manage) */
        put: operations["updateRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The permission catalogue (identity.role.read) */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: string;
            password: string;
        };
        SessionResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** Format: date-time */
            expires_at: string;
            account: components["schemas"]["Account"];
        };
        UpdateMeRequest: {
            name: string;
            /**
             * Format: int32
             * @description The version you last read; a newer one returns 409
             */
            version: number;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        Account: {
            id: components["schemas"]["ID"];
            email: string;
            name: string;
            member_id?: components["schemas"]["ID"];
            active: boolean;
            status: components["schemas"]["AccountStatus"];
            /** Format: int32 */
            version: number;
            /**
             * Format: date-time
             * @description Last time the account signed in (refreshing a session doesn't count)
             */
            last_sign_in_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RoleSummary: {
            id: components["schemas"]["ID"];
            name: string;
        };
        AccountDetail: components["schemas"]["Account"] & {
            roles: components["schemas"]["RoleSummary"][];
            /**
             * Format: int64
             * @description Sessions still usable; only on GET /accounts/{accountID}
             */
            active_sessions?: number;
            /**
             * Format: date-time
             * @description When the pending invitation link stops working; only on GET /accounts/{accountID}
             */
            invite_expires_at?: string;
        };
        AccountListItem: components["schemas"]["Account"] & {
            roles: components["schemas"]["RoleSummary"][];
            /**
             * Format: date-time
             * @description When the pending invitation link stops working (invited accounts)
             */
            invite_expires_at?: string;
        };
        /**
         * @description invited = has not set a password yet
         * @enum {string}
         */
        AccountStatus: "invited" | "active" | "disabled";
        /** @description Accounts per status for the same q and role_id, ignoring active and status */
        AccountStatusCounts: {
            /** Format: int64 */
            invited: number;
            /** Format: int64 */
            active: number;
            /** Format: int64 */
            disabled: number;
        };
        AccountList: components["schemas"]["Paged"] & {
            items: components["schemas"]["AccountListItem"][];
            status_counts: components["schemas"]["AccountStatusCounts"];
        };
        Me: {
            account: components["schemas"]["Account"];
            roles: components["schemas"]["RoleSummary"][];
            permissions: string[];
        };
        /** @description The account starts invited; the user sets a password from the emailed link */
        CreateAccountRequest: {
            email: string;
            name: string;
            member_id?: components["schemas"]["ID"];
            role_ids?: components["schemas"]["ID"][];
        };
        UpdateAccountRequest: {
            name?: string;
            member_id?: components["schemas"]["ID"];
            /** @description Remove the member link */
            clear_member_id?: boolean;
            /**
             * Format: int32
             * @description The version you last read; a newer one returns 409
             */
            version: number;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        SetPasswordRequest: {
            token: string;
            new_password: string;
        };
        AssignRolesRequest: {
            role_ids: components["schemas"]["ID"][];
        };
        Role: {
            id: components["schemas"]["ID"];
            name: string;
            description: string;
            is_system: boolean;
            permissions: string[];
            /**
             * Format: int64
             * @description Accounts that hold the role and are not disabled; on GET /roles and GET /roles/{roleID}
             */
            member_count?: number;
        };
        CreateRoleRequest: {
            name: string;
            description?: string;
            permissions?: string[];
        };
        UpdateRoleRequest: {
            name?: string;
            description?: string;
        };
        RolePermissionsRequest: {
            permissions: string[];
        };
        Permission: {
            code: string;
            description: string;
        };
        FieldError: {
            /** @description Đường dẫn JSON của field, vd address.city */
            field: string;
            detail: string;
        };
        Problem: {
            /**
             * @description Định danh loại lỗi, ổn định, client so sánh bằng field này
             * @example /errors/asset-not-available
             */
            type: string;
            /** @description Câu ngắn, giống nhau mọi lần xảy ra */
            title: string;
            status: number;
            /** @description Giải thích cho lần xảy ra này */
            detail?: string;
            /** @description Field sai, khi status là 422 */
            errors?: components["schemas"]["FieldError"][];
        };
        /** Format: uuid */
        ID: string;
        Paged: {
            /** Format: int64 */
            total: number;
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AccountID: components["schemas"]["ID"];
        RoleID: components["schemas"]["ID"];
        RefreshCookie: string;
        UserAgent: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: {
        /** @description The refresh-token cookie (HttpOnly, SameSite=Strict, Path=/api/v1/auth) */
        SetCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: {
                "User-Agent"?: components["parameters"]["UserAgent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; the refresh token is set as an HttpOnly cookie */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                storeit_refresh?: components["parameters"]["RefreshCookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description New access token; the cookie holds the next refresh token */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Missing, invalid, expired, revoked or reused refresh token; the cookie is cleared */
            401: {
                headers: {
                    "Set-Cookie": components["headers"]["SetCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                storeit_refresh?: components["parameters"]["RefreshCookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the cookie is cleared */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SetCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                storeit_refresh?: components["parameters"]["RefreshCookie"];
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description If the email belongs to an active account */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    setPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password set; sign in with it */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Your account after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description Search by name or email */
                q?: string;
                active?: boolean;
                /** @description Only accounts with this status */
                status?: components["schemas"]["AccountStatus"];
                /** @description Only accounts holding this role */
                role_id?: components["schemas"]["ID"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    disableAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    signOutAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int64
                         * @description Number of sessions that were still live
                         */
                        revoked: number;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    enableAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    resendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    sendPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    assignRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: components["parameters"]["AccountID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesRequest"];
            };
        };
        responses: {
            /** @description Account with its new roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleID: components["parameters"]["RoleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleID: components["parameters"]["RoleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleID: components["parameters"]["RoleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Updated role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleID: components["parameters"]["RoleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePermissionsRequest"];
            };
        };
        responses: {
            /** @description Role with its new permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Permission"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
