/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/asset-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List asset types (inventory.asset.read) */
        get: operations["listAssetTypes"];
        put?: never;
        /** Create an asset type, optionally with attributes (inventory.type.manage) */
        post: operations["createAssetType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset-types/{typeID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        /** Get an asset type with its attributes and options (inventory.asset.read) */
        get: operations["getAssetType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename or describe an asset type (inventory.type.manage) */
        patch: operations["updateAssetType"];
        trace?: never;
    };
    "/asset-types/{typeID}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop offering an asset type for new assets (inventory.type.manage) */
        post: operations["archiveAssetType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset-types/{typeID}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer an archived asset type again (inventory.type.manage) */
        post: operations["restoreAssetType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset-types/{typeID}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a custom attribute (inventory.type.manage) */
        post: operations["addAttribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset-types/{typeID}/attributes/{attributeID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a custom attribute; stored values are kept (inventory.type.manage) */
        delete: operations["removeAttribute"];
        options?: never;
        head?: never;
        /**
         * Change label, unit, data type, required or position (inventory.type.manage)
         * @description Data type and unit can change only while no asset has a value; send "unit":"" to remove the unit.
         */
        patch: operations["updateAttribute"];
        trace?: never;
    };
    "/asset-types/{typeID}/attributes/{attributeID}/options": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an option to a select attribute (inventory.type.manage) */
        post: operations["addOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset-types/{typeID}/attributes/{attributeID}/options/{optionID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
                optionID: components["parameters"]["OptionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an option; assets using it keep it (inventory.type.manage) */
        delete: operations["removeOption"];
        options?: never;
        head?: never;
        /** Rename or move an option (inventory.type.manage) */
        patch: operations["updateOption"];
        trace?: never;
    };
    "/asset-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List asset statuses (inventory.asset.read) */
        get: operations["listStatuses"];
        put?: never;
        /** Create a status (inventory.status.manage) */
        post: operations["createStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset-statuses/{statusID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusID: components["parameters"]["StatusID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename, move or make default of its kind (inventory.status.manage) */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/asset-statuses/{statusID}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusID: components["parameters"]["StatusID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop offering a status (inventory.status.manage) */
        post: operations["archiveStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse, search and filter assets (inventory.asset.read) */
        get: operations["listAssets"];
        put?: never;
        /** Create an asset (inventory.asset.manage) */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{assetID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetID: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        /** Get an asset with its custom attributes (inventory.asset.read) */
        get: operations["getAsset"];
        /**
         * Replace an asset's fields and attribute values (inventory.asset.manage)
         * @description Full replacement. Omitted optional fields and attributes are cleared; status_id omitted keeps the current status.
         */
        put: operations["updateAsset"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{assetID}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetID: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire an asset; it keeps its tag (inventory.asset.manage) */
        post: operations["retireAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{assetID}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetID: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a retired asset to the default available status (inventory.asset.manage) */
        post: operations["restoreAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DataType: "text" | "number" | "date" | "boolean" | "select";
        /** @enum {string} */
        StatusKind: "available" | "in_use" | "unavailable" | "retired";
        AssetType: {
            id: components["schemas"]["ID"];
            code: string;
            name: string;
            description: string;
            is_system: boolean;
            /** Format: date-time */
            archived_at?: string;
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description Assets of this type that are not retired; only with `with_counts=true`
             */
            asset_count?: number;
        };
        AssetTypeDetail: components["schemas"]["AssetType"] & {
            /** @description All attributes in display order, including removed ones (removed = true) */
            attributes: components["schemas"]["Attribute"][];
        };
        Attribute: {
            id: components["schemas"]["ID"];
            key: string;
            label: string;
            data_type: components["schemas"]["DataType"];
            /** @description Only for number attributes */
            unit?: string;
            is_required: boolean;
            /** Format: int32 */
            position: number;
            removed: boolean;
            options: components["schemas"]["Option"][];
        };
        Option: {
            id: components["schemas"]["ID"];
            label: string;
            /** Format: int32 */
            position: number;
            removed: boolean;
        };
        NewAttribute: {
            key: string;
            label: string;
            data_type: components["schemas"]["DataType"];
            unit?: string;
            is_required?: boolean;
            /** Format: int32 */
            position?: number;
            options?: string[];
        };
        CreateAssetTypeRequest: {
            code: string;
            name: string;
            description?: string;
            attributes?: components["schemas"]["NewAttribute"][];
        };
        UpdateAssetTypeRequest: {
            name?: string;
            description?: string;
            /** Format: int32 */
            version: number;
        };
        UpdateAttributeRequest: {
            label?: string;
            /** @description "" removes the unit */
            unit?: string;
            data_type?: components["schemas"]["DataType"];
            is_required?: boolean;
            /** Format: int32 */
            position?: number;
        };
        OptionRequest: {
            label: string;
            /** Format: int32 */
            position?: number;
        };
        UpdateOptionRequest: {
            label?: string;
            /** Format: int32 */
            position?: number;
        };
        Status: {
            id: components["schemas"]["ID"];
            name: string;
            kind: components["schemas"]["StatusKind"];
            is_default: boolean;
            is_system: boolean;
            /** Format: int32 */
            position: number;
            /** Format: date-time */
            archived_at?: string;
        };
        CreateStatusRequest: {
            name: string;
            kind: components["schemas"]["StatusKind"];
            /** Format: int32 */
            position?: number;
        };
        UpdateStatusRequest: {
            name?: string;
            /** Format: int32 */
            position?: number;
            /** @description Make this the default status of its kind (moves the flag) */
            make_default?: boolean;
        };
        AssetListItem: {
            id: components["schemas"]["ID"];
            tag: string;
            name: string;
            asset_type_id: components["schemas"]["ID"];
            asset_type_name: string;
            status_id: components["schemas"]["ID"];
            status_name: string;
            status_kind: components["schemas"]["StatusKind"];
            location_id?: components["schemas"]["ID"];
            holder_member_id?: components["schemas"]["ID"];
            /** Format: date */
            purchase_date?: string;
            /** Format: date-time */
            retired_at?: string;
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            updated_at: string;
            /** @description Chỉ có khi lọc theo `type_id`; như trong chi tiết tài sản. */
            attributes?: components["schemas"]["AttributeValue"][];
        };
        AssetList: components["schemas"]["Paged"] & {
            items: components["schemas"]["AssetListItem"][];
        };
        TypeSummary: {
            id: components["schemas"]["ID"];
            code: string;
            name: string;
        };
        StatusSummary: {
            id: components["schemas"]["ID"];
            name: string;
            kind: components["schemas"]["StatusKind"];
        };
        AttributeValue: {
            key: string;
            label: string;
            data_type: components["schemas"]["DataType"];
            unit?: string;
            /** @description string (text, date YYYY-MM-DD, select option id), number or boolean; null when empty */
            value: unknown;
            option_label?: string;
            option_removed?: boolean;
        };
        AssetDetail: {
            id: components["schemas"]["ID"];
            tag: string;
            name: string;
            description: string;
            asset_type: components["schemas"]["TypeSummary"];
            status: components["schemas"]["StatusSummary"];
            location_id?: components["schemas"]["ID"];
            holder_member_id?: components["schemas"]["ID"];
            /** Format: date */
            purchase_date?: string;
            /** Format: date-time */
            retired_at?: string;
            retired_reason?: string;
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Active attributes of the asset's type in display order, with their values */
            attributes: components["schemas"]["AttributeValue"][];
        };
        CreateAssetRequest: {
            tag: string;
            name: string;
            description?: string;
            asset_type_id: components["schemas"]["ID"];
            status_id?: components["schemas"]["ID"];
            location_id?: components["schemas"]["ID"];
            holder_member_id?: components["schemas"]["ID"];
            /** Format: date */
            purchase_date?: string;
            attributes?: components["schemas"]["AttributeValues"];
        };
        UpdateAssetRequest: {
            name: string;
            description?: string;
            asset_type_id: components["schemas"]["ID"];
            status_id?: components["schemas"]["ID"];
            location_id?: components["schemas"]["ID"];
            holder_member_id?: components["schemas"]["ID"];
            /** Format: date */
            purchase_date?: string;
            attributes?: components["schemas"]["AttributeValues"];
            /** Format: int32 */
            version: number;
        };
        /** @description Attribute key -> value (string, number, boolean; select = option id; date = YYYY-MM-DD) */
        AttributeValues: {
            [key: string]: unknown;
        };
        RetireAssetRequest: {
            reason?: string;
            /** Format: int32 */
            version: number;
        };
        VersionRequest: {
            /** Format: int32 */
            version: number;
        };
        FieldError: {
            /** @description Đường dẫn JSON của field, vd address.city */
            field: string;
            detail: string;
        };
        Problem: {
            /**
             * @description Định danh loại lỗi, ổn định, client so sánh bằng field này
             * @example /errors/asset-not-available
             */
            type: string;
            /** @description Câu ngắn, giống nhau mọi lần xảy ra */
            title: string;
            status: number;
            /** @description Giải thích cho lần xảy ra này */
            detail?: string;
            /** @description Field sai, khi status là 422 */
            errors?: components["schemas"]["FieldError"][];
        };
        /** Format: uuid */
        ID: string;
        Paged: {
            /** Format: int64 */
            total: number;
        };
    };
    responses: {
        /** @description Error (RFC 9457 problem details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        TypeID: components["schemas"]["ID"];
        AttributeID: components["schemas"]["ID"];
        OptionID: components["schemas"]["ID"];
        StatusID: components["schemas"]["ID"];
        AssetID: components["schemas"]["ID"];
        IncludeArchived: boolean;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAssetTypes: {
        parameters: {
            query?: {
                include_archived?: components["parameters"]["IncludeArchived"];
                /** @description Add `asset_count` (assets not retired) to each type. */
                with_counts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset types without attributes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AssetType"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAssetType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetTypeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAssetType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateAssetType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetTypeRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    archiveAssetType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreAssetType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    addAttribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAttribute"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    removeAttribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateAttribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttributeRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    addOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionRequest"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Option"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    removeOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
                optionID: components["parameters"]["OptionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeID: components["parameters"]["TypeID"];
                attributeID: components["parameters"]["AttributeID"];
                optionID: components["parameters"]["OptionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOptionRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Option"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listStatuses: {
        parameters: {
            query?: {
                include_archived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Status"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStatusRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusID: components["parameters"]["StatusID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatusRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    archiveStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusID: components["parameters"]["StatusID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring of tag or name */
                q?: string;
                /** @description Lọc theo loại; khi có, mỗi dòng kèm `attributes` (các cột của loại). */
                type_id?: components["schemas"]["ID"];
                status_id?: components["schemas"]["ID"];
                status_kind?: components["schemas"]["StatusKind"];
                location_id?: components["schemas"]["ID"];
                holder_member_id?: components["schemas"]["ID"];
                include_retired?: boolean;
                /**
                 * @description Lọc theo thuộc tính tuỳ chỉnh, cần `type_id`; lặp lại để kết hợp (AND).
                 *     Dạng `<key>:<op>:<value>`. Toán tử theo kiểu: text `eq` (không phân biệt
                 *     hoa thường), `contains`; number và date `eq`, `gt`, `gte`, `lt`, `lte`;
                 *     boolean `eq` (`true`/`false`); select `eq` (id option), `in` (id ngăn
                 *     bằng dấu phẩy). Ví dụ `attr=ram_gb:gte:16&attr=os:eq:<option id>`.
                 */
                attr?: string[];
                /**
                 * @description `tag`, `name`, `purchase_date`, `updated_at`, `asset_type` (tên loại),
                 *     `status` (thứ tự status như `GET /asset-statuses`) hoặc `attributes.<key>`
                 *     (cần `type_id`; tài sản không có giá trị ở cuối); tiền tố `-` là giảm dần.
                 *     Mặc định `tag`.
                 */
                sort?: string;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of assets; with type_id each item also carries its attribute values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetID: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetID: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    retireAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetID: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetireAssetRequest"];
            };
        };
        responses: {
            /** @description Retired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetID: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description Restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
