// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "storeit/internal/platform/web/apicommon"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SessionResponseTokenType.
const (
	Bearer SessionResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the SessionResponseTokenType enum.
func (e SessionResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Active    bool             `json:"active"`
	CreatedAt time.Time        `json:"created_at"`
	Email     string           `json:"email"`
	Id        externalRef0.ID  `json:"id"`
	MemberId  *externalRef0.ID `json:"member_id,omitempty"`
	Name      string           `json:"name"`
	UpdatedAt time.Time        `json:"updated_at"`
	Version   int32            `json:"version"`
}

// AccountDetail defines model for AccountDetail.
type AccountDetail struct {
	Active    bool             `json:"active"`
	CreatedAt time.Time        `json:"created_at"`
	Email     string           `json:"email"`
	Id        externalRef0.ID  `json:"id"`
	MemberId  *externalRef0.ID `json:"member_id,omitempty"`
	Name      string           `json:"name"`
	Roles     []RoleSummary    `json:"roles"`
	UpdatedAt time.Time        `json:"updated_at"`
	Version   int32            `json:"version"`
}

// AccountList defines model for AccountList.
type AccountList struct {
	Items []Account `json:"items"`
	Total int64     `json:"total"`
}

// AssignRolesRequest defines model for AssignRolesRequest.
type AssignRolesRequest struct {
	RoleIds []externalRef0.ID `json:"role_ids"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Email    string             `json:"email"`
	MemberId *externalRef0.ID   `json:"member_id,omitempty"`
	Name     string             `json:"name"`
	Password string             `json:"password"`
	RoleIds  *[]externalRef0.ID `json:"role_ids,omitempty"`
}

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	Description *string   `json:"description,omitempty"`
	Name        string    `json:"name"`
	Permissions *[]string `json:"permissions,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	Account     Account       `json:"account"`
	Permissions []string      `json:"permissions"`
	Roles       []RoleSummary `json:"roles"`
}

// Permission defines model for Permission.
type Permission struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
}

// Role defines model for Role.
type Role struct {
	Description string          `json:"description"`
	Id          externalRef0.ID `json:"id"`
	IsSystem    bool            `json:"is_system"`
	Name        string          `json:"name"`
	Permissions []string        `json:"permissions"`
}

// RolePermissionsRequest defines model for RolePermissionsRequest.
type RolePermissionsRequest struct {
	Permissions []string `json:"permissions"`
}

// RoleSummary defines model for RoleSummary.
type RoleSummary struct {
	Id   externalRef0.ID `json:"id"`
	Name string          `json:"name"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	AccessToken string                   `json:"access_token"`
	Account     Account                  `json:"account"`
	ExpiresAt   time.Time                `json:"expires_at"`
	TokenType   SessionResponseTokenType `json:"token_type"`
}

// SessionResponseTokenType defines model for SessionResponse.TokenType.
type SessionResponseTokenType string

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	// ClearMemberId Remove the member link
	ClearMemberId *bool            `json:"clear_member_id,omitempty"`
	MemberId      *externalRef0.ID `json:"member_id,omitempty"`
	Name          *string          `json:"name,omitempty"`

	// Version The version you last read; a newer one returns 409
	Version int32 `json:"version"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// AccountID defines model for AccountID.
type AccountID = externalRef0.ID

// RefreshCookie defines model for RefreshCookie.
type RefreshCookie = string

// RoleID defines model for RoleID.
type RoleID = externalRef0.ID

// UserAgent defines model for UserAgent.
type UserAgent = string

// Problem defines model for Problem.
type Problem = externalRef0.Problem

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	Page     *externalRef0.Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *externalRef0.PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Q Search by name or email
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Active *bool   `form:"active,omitempty" json:"active,omitempty"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	UserAgent *UserAgent `json:"User-Agent,omitempty"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	StoreitRefresh *RefreshCookie `form:"storeit_refresh,omitempty" json:"storeit_refresh,omitempty"`
}

// ChangePasswordParams defines parameters for ChangePassword.
type ChangePasswordParams struct {
	StoreitRefresh *RefreshCookie `form:"storeit_refresh,omitempty" json:"storeit_refresh,omitempty"`
}

// RefreshParams defines parameters for Refresh.
type RefreshParams struct {
	StoreitRefresh *RefreshCookie `form:"storeit_refresh,omitempty" json:"storeit_refresh,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// AssignRolesJSONRequestBody defines body for AssignRoles for application/json ContentType.
type AssignRolesJSONRequestBody = AssignRolesRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = UpdateRoleRequest

// UpdateRolePermissionsJSONRequestBody defines body for UpdateRolePermissions for application/json ContentType.
type UpdateRolePermissionsJSONRequestBody = RolePermissionsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAccounts List accounts (identity.account.read)
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams)
	// CreateAccount Create an account (identity.account.manage)
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// GetAccount Get an account with its roles (identity.account.read)
	// (GET /accounts/{accountID})
	GetAccount(w http.ResponseWriter, r *http.Request, accountID AccountID)
	// UpdateAccount Update name or member link (identity.account.manage)
	// (PATCH /accounts/{accountID})
	UpdateAccount(w http.ResponseWriter, r *http.Request, accountID AccountID)
	// DisableAccount Disable an account and sign out all its devices (identity.account.manage)
	// (POST /accounts/{accountID}/disable)
	DisableAccount(w http.ResponseWriter, r *http.Request, accountID AccountID)
	// EnableAccount Enable a disabled account (identity.account.manage)
	// (POST /accounts/{accountID}/enable)
	EnableAccount(w http.ResponseWriter, r *http.Request, accountID AccountID)
	// ResetPassword Set a new password and sign out all the account's devices (identity.account.manage)
	// (PUT /accounts/{accountID}/password)
	ResetPassword(w http.ResponseWriter, r *http.Request, accountID AccountID)
	// AssignRoles Replace the account's roles (identity.account.manage)
	// (PUT /accounts/{accountID}/roles)
	AssignRoles(w http.ResponseWriter, r *http.Request, accountID AccountID)
	// Login Sign in with email and password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request, params LoginParams)
	// Logout Sign out this device
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)
	// ChangePassword Change your own password; signs out your other devices
	// (PUT /auth/password)
	ChangePassword(w http.ResponseWriter, r *http.Request, params ChangePasswordParams)
	// Refresh Rotate the refresh cookie and get a new access token
	// (POST /auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request, params RefreshParams)
	// GetMe The signed-in account with its roles and permissions
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// ListPermissions The permission catalogue (identity.role.read)
	// (GET /permissions)
	ListPermissions(w http.ResponseWriter, r *http.Request)
	// ListRoles Roles with their permissions (identity.role.read)
	// (GET /roles)
	ListRoles(w http.ResponseWriter, r *http.Request)
	// CreateRole Create a role (identity.role.manage)
	// (POST /roles)
	CreateRole(w http.ResponseWriter, r *http.Request)
	// DeleteRole Delete an unassigned custom role (identity.role.manage)
	// (DELETE /roles/{roleID})
	DeleteRole(w http.ResponseWriter, r *http.Request, roleID RoleID)
	// GetRole Get a role (identity.role.read)
	// (GET /roles/{roleID})
	GetRole(w http.ResponseWriter, r *http.Request, roleID RoleID)
	// UpdateRole Rename or describe a role; system roles cannot be renamed (identity.role.manage)
	// (PATCH /roles/{roleID})
	UpdateRole(w http.ResponseWriter, r *http.Request, roleID RoleID)
	// UpdateRolePermissions Replace the role's permissions (identity.role.manage)
	// (PUT /roles/{roleID}/permissions)
	UpdateRolePermissions(w http.ResponseWriter, r *http.Request, roleID RoleID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListAccounts List accounts (identity.account.read)
// (GET /accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateAccount Create an account (identity.account.manage)
// (POST /accounts)
func (_ Unimplemented) CreateAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAccount Get an account with its roles (identity.account.read)
// (GET /accounts/{accountID})
func (_ Unimplemented) GetAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateAccount Update name or member link (identity.account.manage)
// (PATCH /accounts/{accountID})
func (_ Unimplemented) UpdateAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DisableAccount Disable an account and sign out all its devices (identity.account.manage)
// (POST /accounts/{accountID}/disable)
func (_ Unimplemented) DisableAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// EnableAccount Enable a disabled account (identity.account.manage)
// (POST /accounts/{accountID}/enable)
func (_ Unimplemented) EnableAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ResetPassword Set a new password and sign out all the account's devices (identity.account.manage)
// (PUT /accounts/{accountID}/password)
func (_ Unimplemented) ResetPassword(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AssignRoles Replace the account's roles (identity.account.manage)
// (PUT /accounts/{accountID}/roles)
func (_ Unimplemented) AssignRoles(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login Sign in with email and password
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request, params LoginParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Sign out this device
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ChangePassword Change your own password; signs out your other devices
// (PUT /auth/password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request, params ChangePasswordParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Rotate the refresh cookie and get a new access token
// (POST /auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request, params RefreshParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe The signed-in account with its roles and permissions
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListPermissions The permission catalogue (identity.role.read)
// (GET /permissions)
func (_ Unimplemented) ListPermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListRoles Roles with their permissions (identity.role.read)
// (GET /roles)
func (_ Unimplemented) ListRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateRole Create a role (identity.role.manage)
// (POST /roles)
func (_ Unimplemented) CreateRole(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteRole Delete an unassigned custom role (identity.role.manage)
// (DELETE /roles/{roleID})
func (_ Unimplemented) DeleteRole(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRole Get a role (identity.role.read)
// (GET /roles/{roleID})
func (_ Unimplemented) GetRole(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateRole Rename or describe a role; system roles cannot be renamed (identity.role.manage)
// (PATCH /roles/{roleID})
func (_ Unimplemented) UpdateRole(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateRolePermissions Replace the role's permissions (identity.role.manage)
// (PUT /roles/{roleID}/permissions)
func (_ Unimplemented) UpdateRolePermissions(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", r.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "active"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountID" -------------
	var accountID AccountID

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountID" -------------
	var accountID AccountID

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableAccount operation middleware
func (siw *ServerInterfaceWrapper) DisableAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountID" -------------
	var accountID AccountID

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableAccount(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnableAccount operation middleware
func (siw *ServerInterfaceWrapper) EnableAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountID" -------------
	var accountID AccountID

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnableAccount(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountID" -------------
	var accountID AccountID

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetPassword(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignRoles operation middleware
func (siw *ServerInterfaceWrapper) AssignRoles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountID" -------------
	var accountID AccountID

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignRoles(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := r.Header

	// ------------- Optional header parameter "User-Agent" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("User-Agent")]; found {
		var UserAgent UserAgent
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "User-Agent", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "User-Agent", valueList[0], &UserAgent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "User-Agent", Err: err})
			return
		}

		params.UserAgent = &UserAgent

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("storeit_refresh"); err == nil {
			var value RefreshCookie
			err = runtime.BindStyledParameterWithOptions("simple", "storeit_refresh", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storeit_refresh", Err: err})
				return
			}
			params.StoreitRefresh = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ChangePasswordParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("storeit_refresh"); err == nil {
			var value RefreshCookie
			err = runtime.BindStyledParameterWithOptions("simple", "storeit_refresh", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storeit_refresh", Err: err})
				return
			}
			params.StoreitRefresh = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("storeit_refresh"); err == nil {
			var value RefreshCookie
			err = runtime.BindStyledParameterWithOptions("simple", "storeit_refresh", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storeit_refresh", Err: err})
				return
			}
			params.StoreitRefresh = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPermissions operation middleware
func (siw *ServerInterfaceWrapper) ListPermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoles operation middleware
func (siw *ServerInterfaceWrapper) ListRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRole operation middleware
func (siw *ServerInterfaceWrapper) CreateRole(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRole(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRole operation middleware
func (siw *ServerInterfaceWrapper) DeleteRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roleID" -------------
	var roleID RoleID

	err = runtime.BindStyledParameterWithOptions("simple", "roleID", chi.URLParam(r, "roleID"), &roleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roleID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRole(w, r, roleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRole operation middleware
func (siw *ServerInterfaceWrapper) GetRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roleID" -------------
	var roleID RoleID

	err = runtime.BindStyledParameterWithOptions("simple", "roleID", chi.URLParam(r, "roleID"), &roleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roleID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRole(w, r, roleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roleID" -------------
	var roleID RoleID

	err = runtime.BindStyledParameterWithOptions("simple", "roleID", chi.URLParam(r, "roleID"), &roleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roleID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRole(w, r, roleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRolePermissions operation middleware
func (siw *ServerInterfaceWrapper) UpdateRolePermissions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roleID" -------------
	var roleID RoleID

	err = runtime.BindStyledParameterWithOptions("simple", "roleID", chi.URLParam(r, "roleID"), &roleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roleID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRolePermissions(w, r, roleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/password", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts", wrapper.CreateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/{accountID}", wrapper.GetAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/accounts/{accountID}", wrapper.UpdateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts/{accountID}/disable", wrapper.DisableAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts/{accountID}/enable", wrapper.EnableAccount)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/accounts/{accountID}/password", wrapper.ResetPassword)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/accounts/{accountID}/roles", wrapper.AssignRoles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/roles", wrapper.ListRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/roles", wrapper.CreateRole)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/roles/{roleID}", wrapper.DeleteRole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/roles/{roleID}", wrapper.GetRole)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/roles/{roleID}", wrapper.UpdateRole)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/roles/{roleID}/permissions", wrapper.UpdateRolePermissions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/permissions", wrapper.ListPermissions)
	})

	return r
}

type ProblemApplicationProblemPlusJSONResponse externalRef0.Problem

type ListAccountsRequestObject struct {
	Params ListAccountsParams
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse AccountList

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountsdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response ListAccountsdefaultApplicationProblemPlusJSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse AccountDetail

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response CreateAccountdefaultApplicationProblemPlusJSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountRequestObject struct {
	AccountID AccountID `json:"accountID"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse AccountDetail

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetAccountdefaultApplicationProblemPlusJSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccountRequestObject struct {
	AccountID AccountID `json:"accountID"`
	Body      *UpdateAccountJSONRequestBody
}

type UpdateAccountResponseObject interface {
	VisitUpdateAccountResponse(w http.ResponseWriter) error
}

type UpdateAccount200JSONResponse AccountDetail

func (response UpdateAccount200JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccountdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response UpdateAccountdefaultApplicationProblemPlusJSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DisableAccountRequestObject struct {
	AccountID AccountID `json:"accountID"`
}

type DisableAccountResponseObject interface {
	VisitDisableAccountResponse(w http.ResponseWriter) error
}

type DisableAccount200JSONResponse AccountDetail

func (response DisableAccount200JSONResponse) VisitDisableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DisableAccountdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response DisableAccountdefaultApplicationProblemPlusJSONResponse) VisitDisableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type EnableAccountRequestObject struct {
	AccountID AccountID `json:"accountID"`
}

type EnableAccountResponseObject interface {
	VisitEnableAccountResponse(w http.ResponseWriter) error
}

type EnableAccount200JSONResponse AccountDetail

func (response EnableAccount200JSONResponse) VisitEnableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EnableAccountdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response EnableAccountdefaultApplicationProblemPlusJSONResponse) VisitEnableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ResetPasswordRequestObject struct {
	AccountID AccountID `json:"accountID"`
	Body      *ResetPasswordJSONRequestBody
}

type ResetPasswordResponseObject interface {
	VisitResetPasswordResponse(w http.ResponseWriter) error
}

type ResetPassword204Response struct {
}

func (response ResetPassword204Response) VisitResetPasswordResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ResetPassworddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response ResetPassworddefaultApplicationProblemPlusJSONResponse) VisitResetPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AssignRolesRequestObject struct {
	AccountID AccountID `json:"accountID"`
	Body      *AssignRolesJSONRequestBody
}

type AssignRolesResponseObject interface {
	VisitAssignRolesResponse(w http.ResponseWriter) error
}

type AssignRoles200JSONResponse AccountDetail

func (response AssignRoles200JSONResponse) VisitAssignRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AssignRolesdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response AssignRolesdefaultApplicationProblemPlusJSONResponse) VisitAssignRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Params LoginParams
	Body   *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    SessionResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LogindefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response LogindefaultApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Params LogoutParams
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type LogoutdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response LogoutdefaultApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePasswordRequestObject struct {
	Params ChangePasswordParams
	Body   *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword204Response struct {
}

func (response ChangePassword204Response) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ChangePassworddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response ChangePassworddefaultApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
	Params RefreshParams
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200ResponseHeaders struct {
	SetCookie *string
}

type Refresh200JSONResponse struct {
	Body    SessionResponse
	Headers Refresh200ResponseHeaders
}

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401ResponseHeaders struct {
	SetCookie *string
}

type Refresh401ApplicationProblemPlusJSONResponse struct {
	Body    externalRef0.Problem
	Headers Refresh401ResponseHeaders
}

func (response Refresh401ApplicationProblemPlusJSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response RefreshdefaultApplicationProblemPlusJSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetMedefaultApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListPermissionsRequestObject struct {
}

type ListPermissionsResponseObject interface {
	VisitListPermissionsResponse(w http.ResponseWriter) error
}

type ListPermissions200JSONResponse []Permission

func (response ListPermissions200JSONResponse) VisitListPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPermissionsdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response ListPermissionsdefaultApplicationProblemPlusJSONResponse) VisitListPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListRolesRequestObject struct {
}

type ListRolesResponseObject interface {
	VisitListRolesResponse(w http.ResponseWriter) error
}

type ListRoles200JSONResponse []Role

func (response ListRoles200JSONResponse) VisitListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRolesdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response ListRolesdefaultApplicationProblemPlusJSONResponse) VisitListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRoleRequestObject struct {
	Body *CreateRoleJSONRequestBody
}

type CreateRoleResponseObject interface {
	VisitCreateRoleResponse(w http.ResponseWriter) error
}

type CreateRole201JSONResponse Role

func (response CreateRole201JSONResponse) VisitCreateRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRoledefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response CreateRoledefaultApplicationProblemPlusJSONResponse) VisitCreateRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRoleRequestObject struct {
	RoleID RoleID `json:"roleID"`
}

type DeleteRoleResponseObject interface {
	VisitDeleteRoleResponse(w http.ResponseWriter) error
}

type DeleteRole204Response struct {
}

func (response DeleteRole204Response) VisitDeleteRoleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteRoledefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response DeleteRoledefaultApplicationProblemPlusJSONResponse) VisitDeleteRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoleRequestObject struct {
	RoleID RoleID `json:"roleID"`
}

type GetRoleResponseObject interface {
	VisitGetRoleResponse(w http.ResponseWriter) error
}

type GetRole200JSONResponse Role

func (response GetRole200JSONResponse) VisitGetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoledefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetRoledefaultApplicationProblemPlusJSONResponse) VisitGetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRoleRequestObject struct {
	RoleID RoleID `json:"roleID"`
	Body   *UpdateRoleJSONRequestBody
}

type UpdateRoleResponseObject interface {
	VisitUpdateRoleResponse(w http.ResponseWriter) error
}

type UpdateRole200JSONResponse Role

func (response UpdateRole200JSONResponse) VisitUpdateRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRoledefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response UpdateRoledefaultApplicationProblemPlusJSONResponse) VisitUpdateRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRolePermissionsRequestObject struct {
	RoleID RoleID `json:"roleID"`
	Body   *UpdateRolePermissionsJSONRequestBody
}

type UpdateRolePermissionsResponseObject interface {
	VisitUpdateRolePermissionsResponse(w http.ResponseWriter) error
}

type UpdateRolePermissions200JSONResponse Role

func (response UpdateRolePermissions200JSONResponse) VisitUpdateRolePermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRolePermissionsdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response UpdateRolePermissionsdefaultApplicationProblemPlusJSONResponse) VisitUpdateRolePermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAccounts List accounts (identity.account.read)
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// CreateAccount Create an account (identity.account.manage)
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// GetAccount Get an account with its roles (identity.account.read)
	// (GET /accounts/{accountID})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// UpdateAccount Update name or member link (identity.account.manage)
	// (PATCH /accounts/{accountID})
	UpdateAccount(ctx context.Context, request UpdateAccountRequestObject) (UpdateAccountResponseObject, error)
	// DisableAccount Disable an account and sign out all its devices (identity.account.manage)
	// (POST /accounts/{accountID}/disable)
	DisableAccount(ctx context.Context, request DisableAccountRequestObject) (DisableAccountResponseObject, error)
	// EnableAccount Enable a disabled account (identity.account.manage)
	// (POST /accounts/{accountID}/enable)
	EnableAccount(ctx context.Context, request EnableAccountRequestObject) (EnableAccountResponseObject, error)
	// ResetPassword Set a new password and sign out all the account's devices (identity.account.manage)
	// (PUT /accounts/{accountID}/password)
	ResetPassword(ctx context.Context, request ResetPasswordRequestObject) (ResetPasswordResponseObject, error)
	// AssignRoles Replace the account's roles (identity.account.manage)
	// (PUT /accounts/{accountID}/roles)
	AssignRoles(ctx context.Context, request AssignRolesRequestObject) (AssignRolesResponseObject, error)
	// Login Sign in with email and password
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Sign out this device
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// ChangePassword Change your own password; signs out your other devices
	// (PUT /auth/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// Refresh Rotate the refresh cookie and get a new access token
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// GetMe The signed-in account with its roles and permissions
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// ListPermissions The permission catalogue (identity.role.read)
	// (GET /permissions)
	ListPermissions(ctx context.Context, request ListPermissionsRequestObject) (ListPermissionsResponseObject, error)
	// ListRoles Roles with their permissions (identity.role.read)
	// (GET /roles)
	ListRoles(ctx context.Context, request ListRolesRequestObject) (ListRolesResponseObject, error)
	// CreateRole Create a role (identity.role.manage)
	// (POST /roles)
	CreateRole(ctx context.Context, request CreateRoleRequestObject) (CreateRoleResponseObject, error)
	// DeleteRole Delete an unassigned custom role (identity.role.manage)
	// (DELETE /roles/{roleID})
	DeleteRole(ctx context.Context, request DeleteRoleRequestObject) (DeleteRoleResponseObject, error)
	// GetRole Get a role (identity.role.read)
	// (GET /roles/{roleID})
	GetRole(ctx context.Context, request GetRoleRequestObject) (GetRoleResponseObject, error)
	// UpdateRole Rename or describe a role; system roles cannot be renamed (identity.role.manage)
	// (PATCH /roles/{roleID})
	UpdateRole(ctx context.Context, request UpdateRoleRequestObject) (UpdateRoleResponseObject, error)
	// UpdateRolePermissions Replace the role's permissions (identity.role.manage)
	// (PUT /roles/{roleID}/permissions)
	UpdateRolePermissions(ctx context.Context, request UpdateRolePermissionsRequestObject) (UpdateRolePermissionsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams) {
	var request ListAccountsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	var request GetAccountRequestObject

	request.AccountID = accountID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccount operation middleware
func (sh *strictHandler) UpdateAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	var request UpdateAccountRequestObject

	request.AccountID = accountID

	var body UpdateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccount(ctx, request.(UpdateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountResponseObject); ok {
		if err := validResponse.VisitUpdateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableAccount operation middleware
func (sh *strictHandler) DisableAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	var request DisableAccountRequestObject

	request.AccountID = accountID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableAccount(ctx, request.(DisableAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableAccountResponseObject); ok {
		if err := validResponse.VisitDisableAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnableAccount operation middleware
func (sh *strictHandler) EnableAccount(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	var request EnableAccountRequestObject

	request.AccountID = accountID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnableAccount(ctx, request.(EnableAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnableAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnableAccountResponseObject); ok {
		if err := validResponse.VisitEnableAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResetPassword operation middleware
func (sh *strictHandler) ResetPassword(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	var request ResetPasswordRequestObject

	request.AccountID = accountID

	var body ResetPasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResetPassword(ctx, request.(ResetPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetPassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResetPasswordResponseObject); ok {
		if err := validResponse.VisitResetPasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AssignRoles operation middleware
func (sh *strictHandler) AssignRoles(w http.ResponseWriter, r *http.Request, accountID AccountID) {
	var request AssignRolesRequestObject

	request.AccountID = accountID

	var body AssignRolesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AssignRoles(ctx, request.(AssignRolesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AssignRoles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AssignRolesResponseObject); ok {
		if err := validResponse.VisitAssignRolesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request, params LoginParams) {
	var request LoginRequestObject

	request.Params = params

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	var request LogoutRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(w http.ResponseWriter, r *http.Request, params ChangePasswordParams) {
	var request ChangePasswordRequestObject

	request.Params = params

	var body ChangePasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx, request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		if err := validResponse.VisitChangePasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request, params RefreshParams) {
	var request RefreshRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPermissions operation middleware
func (sh *strictHandler) ListPermissions(w http.ResponseWriter, r *http.Request) {
	var request ListPermissionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPermissions(ctx, request.(ListPermissionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPermissions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPermissionsResponseObject); ok {
		if err := validResponse.VisitListPermissionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRoles operation middleware
func (sh *strictHandler) ListRoles(w http.ResponseWriter, r *http.Request) {
	var request ListRolesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRoles(ctx, request.(ListRolesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRoles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRolesResponseObject); ok {
		if err := validResponse.VisitListRolesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRole operation middleware
func (sh *strictHandler) CreateRole(w http.ResponseWriter, r *http.Request) {
	var request CreateRoleRequestObject

	var body CreateRoleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRole(ctx, request.(CreateRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRoleResponseObject); ok {
		if err := validResponse.VisitCreateRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteRole operation middleware
func (sh *strictHandler) DeleteRole(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	var request DeleteRoleRequestObject

	request.RoleID = roleID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRole(ctx, request.(DeleteRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRoleResponseObject); ok {
		if err := validResponse.VisitDeleteRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRole operation middleware
func (sh *strictHandler) GetRole(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	var request GetRoleRequestObject

	request.RoleID = roleID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRole(ctx, request.(GetRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRoleResponseObject); ok {
		if err := validResponse.VisitGetRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRole operation middleware
func (sh *strictHandler) UpdateRole(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	var request UpdateRoleRequestObject

	request.RoleID = roleID

	var body UpdateRoleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRole(ctx, request.(UpdateRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRoleResponseObject); ok {
		if err := validResponse.VisitUpdateRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRolePermissions operation middleware
func (sh *strictHandler) UpdateRolePermissions(w http.ResponseWriter, r *http.Request, roleID RoleID) {
	var request UpdateRolePermissionsRequestObject

	request.RoleID = roleID

	var body UpdateRolePermissionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRolePermissions(ctx, request.(UpdateRolePermissionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRolePermissions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRolePermissionsResponseObject); ok {
		if err := validResponse.VisitUpdateRolePermissionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FtPbxu5Ff8qBFtgE3RsyY7T7SrYgzfZpF4kG0PKoofAEOiZZw03M+SE5NhWDX2CokD3UPRUYLd72ENR",
	"tL3axyz6PfRNCpLzV8PRH3vkpjdJMyTf+/3ee3zvkbrCPo8TzoApiQdXOAQSgDAfR6Cecv6Ogv4SgPQF",
	"TRTlDA/wmxCQgDMBMtxR/B0w5Js30YPfKpW8ZtHUQyMSw4gq+HykBPWVh46JCj/vkYT2zvd6JFXhQ+xh",
	"6YcQE72CmiaAB1gqQdkEz2YzDydEkBhUJs+h7/OUqaNn+gvVYiREhdjDjMR6JCmee1jA+5QKCPBAiRSq",
	"y/xSwBke4F/0Sr179qnUso19HsecjY+eYS3B0CpZ4mDWtcqWK0vFBVA1ziCpqRWTy5fAJirEg73933gN",
	"NT085BG0KiXsw+40+kaCOJwAU8WClvJySf3Gjn1lGT8erkx+TCYlPO9TENNyvkQ/q84UwBlJI4UHex6O",
	"KaNxGpvP2QqUKZiAcC0xor9fusxY6hecaz3ue5oLu9h+v79i6ZlGXCacSTDGdyz4aQSx/uhzpjL8SJJE",
	"1CfaK3qJfeNX30rtIlebE5QvYRav+9uXQnCBHgyfP0WfHTz+FGVroQAUoZF8aLDKpqy4iv6YCJ6AUNSq",
	"QXxFz6FC5ynnERCGZx72BRAFwZiYcWdcxPoTDoiCHUVjjeuCDXgYYkIjh3V4mAYb2qaHY4hPQYxvMdKa",
	"gEOKNAk21ukchKSWw2IAZerRPnaaaOmYb7XSOSaZUF4OeTlvDemaiCfFAvz0W/CVliaj8plh2lAYRa/P",
	"8ODtcohyC5h5iyagI4r5QBXEchXUOjiN0jgmYqqlycQjQpBpQ3s7c1OJk1KNl1Sq9ZVY8P7AoU2hxFra",
	"lKgs18RO1qKJlHTCNC5yCO9TkA4300iMabC+YE1fIJdHdqAOXCthN4u5zOdpSNgEjomUF1wErQL7qRDA",
	"1DjJXlzcufr7ByZgFj84/IbBRdv4T/fro/dd+2BVp4Y8C9M7VTVelVHcqmkRsSri7T+ua/fIod3dg1N1",
	"wWz/WQbnraH07tf8FsLdGhRp32nlp7bx1TR/3O+7rK6J7t466IKIqdTxuI5Sk/cCif3+KiiMLC69X/IJ",
	"ZZub5Lo2sYZ7tpC2lK1X4EogisxizUC7NtJ1aL0tblS5EvkadSFdUBwXzx2xkwfu5GPBlFdEPD1LfYxL",
	"kCFIUCvDeVdheKl5aMRX+m8XeSGVYzmVymbfzby1Nfm7peW5crosuFWVq8q12oA0WKURtWcOW4lL6wiX",
	"+05Dou7S8VZgXTKNwAg8zIowZyQCKcem/eBEaPNQBZcJFSA3qhbM+mP78xUGpgvKt/gLIAJERbEWDGpK",
	"1CarSVMq44LqG1NBrEp8/AiIGNfSmHqROYSYnwNSISD7Foooe1fqXHG5e0+GKjVZsxOVPURTnqKISIUE",
	"kOAJIojBBQjEGSABKhVMooP+Z9jbuKzLV28H/3+f0swcslXQf04hCkwbwSWfaqviz/SwJuo//+k//5rf",
	"/JVNUDC//jtDX41ef438+c1PBJkRHjoPEAkCAVLu+lRN8SpHsAt5uSwny7Wx7bKCxjQ1saQZARbrx4bq",
	"iisSLVb6vz7Ale5Qf6V52ElWiFxpILWhX8f4BZ1f/0iRCj/8ww+RH3IUza9/Yuhyfv3jFAmC2Ifvp86e",
	"jGa5aXjYmACShHroXUiRVESlEkUfvkcH+9oJNq0UKiblyN7s9BWjKtDzsKIqcnSVn374W4rYZH79T+ah",
	"CZ3ffMcmiIUkRfH85o90QX9nMM7C8KK1zm/+wEIUEBaiiM+vf9Bz3fyFemh+82eGfv7OPPeQH1FgCkmO",
	"5IcfWIhO59f/ZhNr0jnccEniREuPexboHpES1A7jaoecExqR0whWmnsW4i0QBVhNE9JAgp8KqqYjzYA1",
	"mVOzuxymOhLk357nBvzV797kHVATte1OVMwcKpXYFiNlZ9zwY9nARwEwRdUUHR4fVdpVA7y329/ta3h5",
	"AowkFA/wo93+7iNTP6jQiNTLNijzZQImCmorN73RowAP8Esq1WH+Ur2339IGKl9Z7ASZRtBmQ0zrWA+r",
	"28YIiPBDdDpFOuoiLlBeGrl6zO/bWvv7jkCuF3NNUjQEG731YoednSy0n/f7/SWt581aztVWnKPXrMFC",
	"/AwVhJo3si66e+ZC1F7Zw/awzDNKQ30xH3pAM0PbzX7a1fv1Q5Oxc+mwnFpjJzsKAam+4MG0M1CczaNZ",
	"3W2VSGHWIGava2KyVq+DGitk0AEjdiZEWE6Lg5WYMDIBe7ZQuHfvqjhmm7W6+gtQVba2a8ftcFUy+zvC",
	"9QJUFasLqkJElUSmfbDUoDeKcuUJpw4ACVF+2AS3lu1vyRucFcVa3nCP9Fohg5yVDmi2MxY7QaUKuo17",
	"9AIqTTJgGjJ3sANnUHxmJ/8Y/CwTpUsmsimrTkdYgCSdMMRThUgUGQcM4Jz6ThdcTQ+w7bHzJftYyLGS",
	"dMmNnRERFCzwfisWqq3KO/GQOmiodUu3FCudHdm1YuVBs1TJ50FCz9oBWSO9cyEGFygHuulIKoScwk/u",
	"5lJFy75zJiunrlvi0XGu+7HteIeL+Yfm1WJ+d0sZQhIRHxasoS3DqdtCqsJexCfUno44I6I5Atu47itv",
	"K9mSqHvaa0dz90z4Yo/bQfmIThgEiLInhpjshhmyl+6oRFL7t9T7ZH7zDhW30+p3+XbKS2wumbKXe+Wt",
	"v0ya2xhV1rLAg7cntWCkow5l1n5NnW2CUbEF1IyJ2zDQak36+abmVL/O56iyHSE5Y4CnylKQ3XSkEpmO",
	"OgQfLdI6vquQ5iG9Am9t03WF2/q1kU5w3kLN7rzbcuet1zfTdlJlm5nQlKcC8QtWGPoTs/9KQ5B9qEIQ",
	"+c5b4Sm/UNrqB8PixmnHjnCvQe5ruED2JMwGtpqjhTwKpPmBwaWqR8COXO9gaRNnmxc7X1EpKZt4iLJz",
	"EtHAQ/bUL/CQgHP+TgcegQSkEoK66v9HwWjIlS6rq/tXJreO/pMiQ62agHUCew7W1mN6BdusrF45TfWp",
	"vZjWYTn1JgQTDiDYoa0tJrNNVk7xDToLdwVau+6Vewd3BWytM6LKZZnm5YpmUhtFddU6QbScEflEkYhP",
	"UqiksRrVvEunoSwKl1YQy9Jj2/CZezVrAtdZ8m+szBidCoGKKiMtsC3v1hslttmqr56433Of3hJ0H+15",
	"w+8i/rXSyxhA78r+TWRms5oIFDgahub3gpdV6ZB9vQtl7Ey6REkZkTbUIT+VisfL9fNaI79bi/7WGc5d",
	"s4vjBKfutzw4yP5CtPLUYIte2bwHc8/FdBtn+TGB6Ia7IeTHA3aZ09xNnyB7GTDbsX3CGFfoVOc8ekSw",
	"gRsv7uy3NwZXbVcytZgYbKE56r72+JGYhv693kzrNhGpttQ0tZ/IZftqaRD1XLp+3+PtiSZWgjjPzSEV",
	"ER7g7I+VeHYy+28AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../api/common.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
