// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_types.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAssetType = `-- name: GetAssetType :one
SELECT id, code, name, description, is_system, archived_at, version, created_at, updated_at FROM inventory.asset_types WHERE id = $1
`

func (q *Queries) GetAssetType(ctx context.Context, id uuid.UUID) (InventoryAssetType, error) {
	row := q.db.QueryRow(ctx, getAssetType, id)
	var i InventoryAssetType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
