// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAssets = `-- name: CountAssets :one
SELECT count(*)
FROM inventory.assets a
JOIN inventory.asset_statuses s ON s.id = a.status_id
WHERE ($1::text IS NULL
       OR a.tag ILIKE '%' || $1::text || '%'
       OR a.name ILIKE '%' || $1::text || '%')
  AND ($2::uuid IS NULL OR a.asset_type_id = $2::uuid)
  AND ($3::uuid IS NULL OR a.status_id = $3::uuid)
  AND ($4::text IS NULL OR s.kind = $4::text)
  AND ($5::uuid IS NULL OR a.location_id = $5::uuid)
  AND ($6::uuid IS NULL OR a.holder_member_id = $6::uuid)
  AND ($7::boolean OR a.retired_at IS NULL)
`

type CountAssetsParams struct {
	Q              *string
	TypeID         *uuid.UUID
	StatusID       *uuid.UUID
	StatusKind     *string
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	IncludeRetired bool
}

func (q *Queries) CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets,
		arg.Q,
		arg.TypeID,
		arg.StatusID,
		arg.StatusKind,
		arg.LocationID,
		arg.HolderMemberID,
		arg.IncludeRetired,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO inventory.assets
    (id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type CreateAssetParams struct {
	ID             uuid.UUID
	Tag            string
	Name           string
	Description    string
	AssetTypeID    uuid.UUID
	StatusID       uuid.UUID
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	PurchaseDate   pgtype.Date
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.Tag,
		arg.Name,
		arg.Description,
		arg.AssetTypeID,
		arg.StatusID,
		arg.LocationID,
		arg.HolderMemberID,
		arg.PurchaseDate,
	)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssetValues = `-- name: DeleteAssetValues :exec
DELETE FROM inventory.asset_attribute_values WHERE asset_id = $1
`

func (q *Queries) DeleteAssetValues(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssetValues, assetID)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at FROM inventory.assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id uuid.UUID) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetForUpdate = `-- name: GetAssetForUpdate :one
SELECT id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at FROM inventory.assets WHERE id = $1 FOR NO KEY UPDATE
`

// NO KEY UPDATE: không chặn insert tham chiếu tài sản (giá trị thuộc tính, sau này là phiếu mượn)
func (q *Queries) GetAssetForUpdate(ctx context.Context, id uuid.UUID) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, getAssetForUpdate, id)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssetValue = `-- name: InsertAssetValue :exec
INSERT INTO inventory.asset_attribute_values
    (asset_id, attribute_id, asset_type_id, data_type, value_text, value_number, value_date, value_bool, value_option_id)
VALUES ($1, $2, $3, $4, $5,
        CAST($6::text AS numeric), $7,
        $8, $9)
`

type InsertAssetValueParams struct {
	AssetID       uuid.UUID
	AttributeID   uuid.UUID
	AssetTypeID   uuid.UUID
	DataType      string
	ValueText     *string
	ValueNumber   *string
	ValueDate     pgtype.Date
	ValueBool     *bool
	ValueOptionID *uuid.UUID
}

func (q *Queries) InsertAssetValue(ctx context.Context, arg InsertAssetValueParams) error {
	_, err := q.db.Exec(ctx, insertAssetValue,
		arg.AssetID,
		arg.AttributeID,
		arg.AssetTypeID,
		arg.DataType,
		arg.ValueText,
		arg.ValueNumber,
		arg.ValueDate,
		arg.ValueBool,
		arg.ValueOptionID,
	)
	return err
}

const listAssetValues = `-- name: ListAssetValues :many
SELECT attribute_id, data_type, value_text, coalesce(value_number::text, '')::text AS value_number,
       value_date, value_bool, value_option_id
FROM inventory.asset_attribute_values
WHERE asset_id = $1
`

type ListAssetValuesRow struct {
	AttributeID   uuid.UUID
	DataType      string
	ValueText     *string
	ValueNumber   string
	ValueDate     pgtype.Date
	ValueBool     *bool
	ValueOptionID *uuid.UUID
}

// value_number đọc dạng text (giữ đúng số thập phân, không qua float); "" là không có số
func (q *Queries) ListAssetValues(ctx context.Context, assetID uuid.UUID) ([]ListAssetValuesRow, error) {
	rows, err := q.db.Query(ctx, listAssetValues, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetValuesRow{}
	for rows.Next() {
		var i ListAssetValuesRow
		if err := rows.Scan(
			&i.AttributeID,
			&i.DataType,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueDate,
			&i.ValueBool,
			&i.ValueOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.tag, a.name, a.description, a.asset_type_id, a.status_id, a.location_id, a.holder_member_id, a.purchase_date, a.retired_at, a.retired_reason, a.version, a.created_at, a.updated_at, t.name AS type_name, s.name AS status_name, s.kind AS status_kind
FROM inventory.assets a
JOIN inventory.asset_types t ON t.id = a.asset_type_id
JOIN inventory.asset_statuses s ON s.id = a.status_id
WHERE ($1::text IS NULL
       OR a.tag ILIKE '%' || $1::text || '%'
       OR a.name ILIKE '%' || $1::text || '%')
  AND ($2::uuid IS NULL OR a.asset_type_id = $2::uuid)
  AND ($3::uuid IS NULL OR a.status_id = $3::uuid)
  AND ($4::text IS NULL OR s.kind = $4::text)
  AND ($5::uuid IS NULL OR a.location_id = $5::uuid)
  AND ($6::uuid IS NULL OR a.holder_member_id = $6::uuid)
  AND ($7::boolean OR a.retired_at IS NULL)
ORDER BY
  CASE WHEN $8::text = 'tag' THEN a.tag END ASC,
  CASE WHEN $8::text = '-tag' THEN a.tag END DESC,
  CASE WHEN $8::text = 'name' THEN lower(a.name) END ASC,
  CASE WHEN $8::text = '-name' THEN lower(a.name) END DESC,
  CASE WHEN $8::text = 'purchase_date' THEN a.purchase_date END ASC NULLS LAST,
  CASE WHEN $8::text = '-purchase_date' THEN a.purchase_date END DESC NULLS LAST,
  CASE WHEN $8::text = 'updated_at' THEN a.updated_at END ASC,
  CASE WHEN $8::text = '-updated_at' THEN a.updated_at END DESC,
  a.tag
LIMIT $10 OFFSET $9
`

type ListAssetsParams struct {
	Q              *string
	TypeID         *uuid.UUID
	StatusID       *uuid.UUID
	StatusKind     *string
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	IncludeRetired bool
	Sort           string
	Off            int32
	Lim            int32
}

type ListAssetsRow struct {
	ID             uuid.UUID
	Tag            string
	Name           string
	Description    string
	AssetTypeID    uuid.UUID
	StatusID       uuid.UUID
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	PurchaseDate   pgtype.Date
	RetiredAt      *time.Time
	RetiredReason  *string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TypeName       string
	StatusName     string
	StatusKind     string
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.Q,
		arg.TypeID,
		arg.StatusID,
		arg.StatusKind,
		arg.LocationID,
		arg.HolderMemberID,
		arg.IncludeRetired,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Name,
			&i.Description,
			&i.AssetTypeID,
			&i.StatusID,
			&i.LocationID,
			&i.HolderMemberID,
			&i.PurchaseDate,
			&i.RetiredAt,
			&i.RetiredReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TypeName,
			&i.StatusName,
			&i.StatusKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuesForAssets = `-- name: ListValuesForAssets :many
SELECT asset_id, attribute_id, data_type, value_text, coalesce(value_number::text, '')::text AS value_number,
       value_date, value_bool, value_option_id
FROM inventory.asset_attribute_values
WHERE asset_id = ANY($1::uuid[])
`

type ListValuesForAssetsRow struct {
	AssetID       uuid.UUID
	AttributeID   uuid.UUID
	DataType      string
	ValueText     *string
	ValueNumber   string
	ValueDate     pgtype.Date
	ValueBool     *bool
	ValueOptionID *uuid.UUID
}

// Giá trị của nhiều tài sản một lần (các dòng của một trang danh sách)
func (q *Queries) ListValuesForAssets(ctx context.Context, assetIds []uuid.UUID) ([]ListValuesForAssetsRow, error) {
	rows, err := q.db.Query(ctx, listValuesForAssets, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListValuesForAssetsRow{}
	for rows.Next() {
		var i ListValuesForAssetsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.AttributeID,
			&i.DataType,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueDate,
			&i.ValueBool,
			&i.ValueOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAsset = `-- name: RestoreAsset :one
UPDATE inventory.assets
SET retired_at = NULL, retired_reason = NULL, status_id = $1,
    version = version + 1, updated_at = now()
WHERE id = $2
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type RestoreAssetParams struct {
	StatusID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RestoreAsset(ctx context.Context, arg RestoreAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, restoreAsset, arg.StatusID, arg.ID)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retireAsset = `-- name: RetireAsset :one
UPDATE inventory.assets
SET retired_at = now(), retired_reason = $1, status_id = $2,
    version = version + 1, updated_at = now()
WHERE id = $3
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type RetireAssetParams struct {
	Reason   *string
	StatusID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RetireAsset(ctx context.Context, arg RetireAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, retireAsset, arg.Reason, arg.StatusID, arg.ID)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE inventory.assets
SET name = $1, description = $2, asset_type_id = $3, status_id = $4,
    location_id = $5, holder_member_id = $6,
    purchase_date = $7, version = version + 1, updated_at = now()
WHERE id = $8
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type UpdateAssetParams struct {
	Name           string
	Description    string
	AssetTypeID    uuid.UUID
	StatusID       uuid.UUID
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	PurchaseDate   pgtype.Date
	ID             uuid.UUID
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.Name,
		arg.Description,
		arg.AssetTypeID,
		arg.StatusID,
		arg.LocationID,
		arg.HolderMemberID,
		arg.PurchaseDate,
		arg.ID,
	)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
