// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAssetsByTypeAndKind = `-- name: CountActiveAssetsByTypeAndKind :many
SELECT a.asset_type_id, s.kind, count(*)::bigint AS n
FROM inventory.assets a
JOIN inventory.asset_statuses s ON s.id = a.status_id
WHERE a.retired_at IS NULL
GROUP BY a.asset_type_id, s.kind
`

type CountActiveAssetsByTypeAndKindRow struct {
	AssetTypeID uuid.UUID
	Kind        string
	N           int64
}

// Số tài sản chưa retire của mỗi loại, tách theo kind của status (sidebar, trang loại)
func (q *Queries) CountActiveAssetsByTypeAndKind(ctx context.Context) ([]CountActiveAssetsByTypeAndKindRow, error) {
	rows, err := q.db.Query(ctx, countActiveAssetsByTypeAndKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveAssetsByTypeAndKindRow{}
	for rows.Next() {
		var i CountActiveAssetsByTypeAndKindRow
		if err := rows.Scan(&i.AssetTypeID, &i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAssets = `-- name: CountAssets :one
SELECT count(*)
FROM inventory.assets a
JOIN inventory.asset_statuses s ON s.id = a.status_id
WHERE ($1::text IS NULL
       OR a.tag ILIKE '%' || $1::text || '%'
       OR a.name ILIKE '%' || $1::text || '%')
  AND ($2::uuid IS NULL OR a.asset_type_id = $2::uuid)
  AND ($3::uuid IS NULL OR a.status_id = $3::uuid)
  AND ($4::text IS NULL OR s.kind = $4::text)
  AND ($5::uuid IS NULL OR a.location_id = $5::uuid)
  AND ($6::uuid IS NULL OR a.holder_member_id = $6::uuid)
  AND ($7::boolean OR a.retired_at IS NULL)
  AND ($8::uuid[] IS NULL OR a.id = ANY($8::uuid[]))
  AND NOT EXISTS (
    -- mọi điều kiện i (f_attrs[i], f_ops[i], f_vals[i]) phải có giá trị khớp; giá trị đã kiểm
    -- ở Go nên ép kiểu trong nhánh CASE không lỗi
    SELECT 1 FROM generate_subscripts($9::text[], 1) AS f(i)
    WHERE NOT EXISTS (
      SELECT 1 FROM inventory.asset_attribute_values v
      WHERE v.asset_id = a.id AND v.attribute_id = ($10::uuid[])[f.i] AND CASE ($9::text[])[f.i]
        WHEN 'text_eq' THEN lower(v.value_text) = lower(($11::text[])[f.i])
        WHEN 'text_contains' THEN v.value_text ILIKE '%' || ($11::text[])[f.i] || '%'
        WHEN 'number_eq' THEN v.value_number = ($11::text[])[f.i]::numeric
        WHEN 'number_gt' THEN v.value_number > ($11::text[])[f.i]::numeric
        WHEN 'number_gte' THEN v.value_number >= ($11::text[])[f.i]::numeric
        WHEN 'number_lt' THEN v.value_number < ($11::text[])[f.i]::numeric
        WHEN 'number_lte' THEN v.value_number <= ($11::text[])[f.i]::numeric
        WHEN 'date_eq' THEN v.value_date = ($11::text[])[f.i]::date
        WHEN 'date_gt' THEN v.value_date > ($11::text[])[f.i]::date
        WHEN 'date_gte' THEN v.value_date >= ($11::text[])[f.i]::date
        WHEN 'date_lt' THEN v.value_date < ($11::text[])[f.i]::date
        WHEN 'date_lte' THEN v.value_date <= ($11::text[])[f.i]::date
        WHEN 'boolean_eq' THEN v.value_bool = ($11::text[])[f.i]::boolean
        WHEN 'select_eq' THEN v.value_option_id = ($11::text[])[f.i]::uuid
        WHEN 'select_in' THEN v.value_option_id = ANY(string_to_array(($11::text[])[f.i], ',')::uuid[])
      END))
`

type CountAssetsParams struct {
	Q              *string
	TypeID         *uuid.UUID
	StatusID       *uuid.UUID
	StatusKind     *string
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	IncludeRetired bool
	Ids            []uuid.UUID
	FOps           []string
	FAttrs         []uuid.UUID
	FVals          []string
}

func (q *Queries) CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets,
		arg.Q,
		arg.TypeID,
		arg.StatusID,
		arg.StatusKind,
		arg.LocationID,
		arg.HolderMemberID,
		arg.IncludeRetired,
		arg.Ids,
		arg.FOps,
		arg.FAttrs,
		arg.FVals,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssetsByStatus = `-- name: CountAssetsByStatus :many
SELECT status_id, count(*)::bigint AS n
FROM inventory.assets
GROUP BY status_id
`

type CountAssetsByStatusRow struct {
	StatusID uuid.UUID
	N        int64
}

// Số tài sản (kể cả đã retire) đang dùng mỗi status
func (q *Queries) CountAssetsByStatus(ctx context.Context) ([]CountAssetsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAssetsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAssetsByStatusRow{}
	for rows.Next() {
		var i CountAssetsByStatusRow
		if err := rows.Scan(&i.StatusID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO inventory.assets
    (id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type CreateAssetParams struct {
	ID             uuid.UUID
	Tag            string
	Name           string
	Description    string
	AssetTypeID    uuid.UUID
	StatusID       uuid.UUID
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	PurchaseDate   pgtype.Date
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.Tag,
		arg.Name,
		arg.Description,
		arg.AssetTypeID,
		arg.StatusID,
		arg.LocationID,
		arg.HolderMemberID,
		arg.PurchaseDate,
	)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssetValues = `-- name: DeleteAssetValues :exec
DELETE FROM inventory.asset_attribute_values WHERE asset_id = $1
`

func (q *Queries) DeleteAssetValues(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssetValues, assetID)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at FROM inventory.assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id uuid.UUID) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetForUpdate = `-- name: GetAssetForUpdate :one
SELECT id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at FROM inventory.assets WHERE id = $1 FOR NO KEY UPDATE
`

// NO KEY UPDATE: không chặn insert tham chiếu tài sản (giá trị thuộc tính, sau này là phiếu mượn)
func (q *Queries) GetAssetForUpdate(ctx context.Context, id uuid.UUID) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, getAssetForUpdate, id)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssetValue = `-- name: InsertAssetValue :exec
INSERT INTO inventory.asset_attribute_values
    (asset_id, attribute_id, asset_type_id, data_type, value_text, value_number, value_date, value_bool, value_option_id)
VALUES ($1, $2, $3, $4, $5,
        CAST($6::text AS numeric), $7,
        $8, $9)
`

type InsertAssetValueParams struct {
	AssetID       uuid.UUID
	AttributeID   uuid.UUID
	AssetTypeID   uuid.UUID
	DataType      string
	ValueText     *string
	ValueNumber   *string
	ValueDate     pgtype.Date
	ValueBool     *bool
	ValueOptionID *uuid.UUID
}

func (q *Queries) InsertAssetValue(ctx context.Context, arg InsertAssetValueParams) error {
	_, err := q.db.Exec(ctx, insertAssetValue,
		arg.AssetID,
		arg.AttributeID,
		arg.AssetTypeID,
		arg.DataType,
		arg.ValueText,
		arg.ValueNumber,
		arg.ValueDate,
		arg.ValueBool,
		arg.ValueOptionID,
	)
	return err
}

const listAssetValues = `-- name: ListAssetValues :many
SELECT attribute_id, data_type, value_text, coalesce(value_number::text, '')::text AS value_number,
       value_date, value_bool, value_option_id
FROM inventory.asset_attribute_values
WHERE asset_id = $1
`

type ListAssetValuesRow struct {
	AttributeID   uuid.UUID
	DataType      string
	ValueText     *string
	ValueNumber   string
	ValueDate     pgtype.Date
	ValueBool     *bool
	ValueOptionID *uuid.UUID
}

// value_number đọc dạng text (giữ đúng số thập phân, không qua float); "" là không có số
func (q *Queries) ListAssetValues(ctx context.Context, assetID uuid.UUID) ([]ListAssetValuesRow, error) {
	rows, err := q.db.Query(ctx, listAssetValues, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetValuesRow{}
	for rows.Next() {
		var i ListAssetValuesRow
		if err := rows.Scan(
			&i.AttributeID,
			&i.DataType,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueDate,
			&i.ValueBool,
			&i.ValueOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.tag, a.name, a.description, a.asset_type_id, a.status_id, a.location_id, a.holder_member_id, a.purchase_date, a.retired_at, a.retired_reason, a.version, a.created_at, a.updated_at, t.name AS type_name, s.name AS status_name, s.kind AS status_kind
FROM inventory.assets a
JOIN inventory.asset_types t ON t.id = a.asset_type_id
JOIN inventory.asset_statuses s ON s.id = a.status_id
LEFT JOIN inventory.asset_attribute_values sv ON sv.asset_id = a.id AND sv.attribute_id = $1::uuid
LEFT JOIN inventory.asset_attribute_options so ON so.id = sv.value_option_id
WHERE ($2::text IS NULL
       OR a.tag ILIKE '%' || $2::text || '%'
       OR a.name ILIKE '%' || $2::text || '%')
  AND ($3::uuid IS NULL OR a.asset_type_id = $3::uuid)
  AND ($4::uuid IS NULL OR a.status_id = $4::uuid)
  AND ($5::text IS NULL OR s.kind = $5::text)
  AND ($6::uuid IS NULL OR a.location_id = $6::uuid)
  AND ($7::uuid IS NULL OR a.holder_member_id = $7::uuid)
  AND ($8::boolean OR a.retired_at IS NULL)
  AND ($9::uuid[] IS NULL OR a.id = ANY($9::uuid[]))
  AND NOT EXISTS (
    -- mọi điều kiện i (f_attrs[i], f_ops[i], f_vals[i]) phải có giá trị khớp; giá trị đã kiểm
    -- ở Go nên ép kiểu trong nhánh CASE không lỗi
    SELECT 1 FROM generate_subscripts($10::text[], 1) AS f(i)
    WHERE NOT EXISTS (
      SELECT 1 FROM inventory.asset_attribute_values v
      WHERE v.asset_id = a.id AND v.attribute_id = ($11::uuid[])[f.i] AND CASE ($10::text[])[f.i]
        WHEN 'text_eq' THEN lower(v.value_text) = lower(($12::text[])[f.i])
        WHEN 'text_contains' THEN v.value_text ILIKE '%' || ($12::text[])[f.i] || '%'
        WHEN 'number_eq' THEN v.value_number = ($12::text[])[f.i]::numeric
        WHEN 'number_gt' THEN v.value_number > ($12::text[])[f.i]::numeric
        WHEN 'number_gte' THEN v.value_number >= ($12::text[])[f.i]::numeric
        WHEN 'number_lt' THEN v.value_number < ($12::text[])[f.i]::numeric
        WHEN 'number_lte' THEN v.value_number <= ($12::text[])[f.i]::numeric
        WHEN 'date_eq' THEN v.value_date = ($12::text[])[f.i]::date
        WHEN 'date_gt' THEN v.value_date > ($12::text[])[f.i]::date
        WHEN 'date_gte' THEN v.value_date >= ($12::text[])[f.i]::date
        WHEN 'date_lt' THEN v.value_date < ($12::text[])[f.i]::date
        WHEN 'date_lte' THEN v.value_date <= ($12::text[])[f.i]::date
        WHEN 'boolean_eq' THEN v.value_bool = ($12::text[])[f.i]::boolean
        WHEN 'select_eq' THEN v.value_option_id = ($12::text[])[f.i]::uuid
        WHEN 'select_in' THEN v.value_option_id = ANY(string_to_array(($12::text[])[f.i], ',')::uuid[])
      END))
ORDER BY
  CASE WHEN $13::text = 'tag' THEN a.tag END ASC,
  CASE WHEN $13::text = '-tag' THEN a.tag END DESC,
  CASE WHEN $13::text = 'name' THEN lower(a.name) END ASC,
  CASE WHEN $13::text = '-name' THEN lower(a.name) END DESC,
  CASE WHEN $13::text = 'purchase_date' THEN a.purchase_date END ASC NULLS LAST,
  CASE WHEN $13::text = '-purchase_date' THEN a.purchase_date END DESC NULLS LAST,
  CASE WHEN $13::text = 'updated_at' THEN a.updated_at END ASC,
  CASE WHEN $13::text = '-updated_at' THEN a.updated_at END DESC,
  CASE WHEN $13::text = 'asset_type' THEN lower(t.name) END ASC,
  CASE WHEN $13::text = '-asset_type' THEN lower(t.name) END DESC,
  CASE WHEN $13::text = 'status' THEN s.position END ASC,
  CASE WHEN $13::text = 'status' THEN lower(s.name) END ASC,
  CASE WHEN $13::text = '-status' THEN s.position END DESC,
  CASE WHEN $13::text = '-status' THEN lower(s.name) END DESC,
  -- theo thuộc tính: không có giá trị luôn ở cuối
  CASE WHEN $13::text = 'attr_text' THEN lower(sv.value_text) END ASC NULLS LAST,
  CASE WHEN $13::text = '-attr_text' THEN lower(sv.value_text) END DESC NULLS LAST,
  CASE WHEN $13::text = 'attr_number' THEN sv.value_number END ASC NULLS LAST,
  CASE WHEN $13::text = '-attr_number' THEN sv.value_number END DESC NULLS LAST,
  CASE WHEN $13::text = 'attr_date' THEN sv.value_date END ASC NULLS LAST,
  CASE WHEN $13::text = '-attr_date' THEN sv.value_date END DESC NULLS LAST,
  CASE WHEN $13::text = 'attr_boolean' THEN sv.value_bool END ASC NULLS LAST,
  CASE WHEN $13::text = '-attr_boolean' THEN sv.value_bool END DESC NULLS LAST,
  CASE WHEN $13::text = 'attr_select' THEN so.position END ASC NULLS LAST,
  CASE WHEN $13::text = '-attr_select' THEN so.position END DESC NULLS LAST,
  a.tag
LIMIT $15 OFFSET $14
`

type ListAssetsParams struct {
	SortAttr       *uuid.UUID
	Q              *string
	TypeID         *uuid.UUID
	StatusID       *uuid.UUID
	StatusKind     *string
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	IncludeRetired bool
	Ids            []uuid.UUID
	FOps           []string
	FAttrs         []uuid.UUID
	FVals          []string
	Sort           string
	Off            int32
	Lim            int32
}

type ListAssetsRow struct {
	ID             uuid.UUID
	Tag            string
	Name           string
	Description    string
	AssetTypeID    uuid.UUID
	StatusID       uuid.UUID
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	PurchaseDate   pgtype.Date
	RetiredAt      *time.Time
	RetiredReason  *string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TypeName       string
	StatusName     string
	StatusKind     string
}

// giá trị của thuộc tính để sắp (sort_attr NULL thì không khớp dòng nào)
func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.SortAttr,
		arg.Q,
		arg.TypeID,
		arg.StatusID,
		arg.StatusKind,
		arg.LocationID,
		arg.HolderMemberID,
		arg.IncludeRetired,
		arg.Ids,
		arg.FOps,
		arg.FAttrs,
		arg.FVals,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Name,
			&i.Description,
			&i.AssetTypeID,
			&i.StatusID,
			&i.LocationID,
			&i.HolderMemberID,
			&i.PurchaseDate,
			&i.RetiredAt,
			&i.RetiredReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TypeName,
			&i.StatusName,
			&i.StatusKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuesForAssets = `-- name: ListValuesForAssets :many
SELECT asset_id, attribute_id, data_type, value_text, coalesce(value_number::text, '')::text AS value_number,
       value_date, value_bool, value_option_id
FROM inventory.asset_attribute_values
WHERE asset_id = ANY($1::uuid[])
`

type ListValuesForAssetsRow struct {
	AssetID       uuid.UUID
	AttributeID   uuid.UUID
	DataType      string
	ValueText     *string
	ValueNumber   string
	ValueDate     pgtype.Date
	ValueBool     *bool
	ValueOptionID *uuid.UUID
}

// Giá trị của nhiều tài sản một lần (các dòng của một trang danh sách)
func (q *Queries) ListValuesForAssets(ctx context.Context, assetIds []uuid.UUID) ([]ListValuesForAssetsRow, error) {
	rows, err := q.db.Query(ctx, listValuesForAssets, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListValuesForAssetsRow{}
	for rows.Next() {
		var i ListValuesForAssetsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.AttributeID,
			&i.DataType,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueDate,
			&i.ValueBool,
			&i.ValueOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAsset = `-- name: RestoreAsset :one
UPDATE inventory.assets
SET retired_at = NULL, retired_reason = NULL, status_id = $1,
    version = version + 1, updated_at = now()
WHERE id = $2
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type RestoreAssetParams struct {
	StatusID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RestoreAsset(ctx context.Context, arg RestoreAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, restoreAsset, arg.StatusID, arg.ID)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retireAsset = `-- name: RetireAsset :one
UPDATE inventory.assets
SET retired_at = now(), retired_reason = $1, status_id = $2,
    version = version + 1, updated_at = now()
WHERE id = $3
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type RetireAssetParams struct {
	Reason   *string
	StatusID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RetireAsset(ctx context.Context, arg RetireAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, retireAsset, arg.Reason, arg.StatusID, arg.ID)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE inventory.assets
SET name = $1, description = $2, asset_type_id = $3, status_id = $4,
    location_id = $5, holder_member_id = $6,
    purchase_date = $7, version = version + 1, updated_at = now()
WHERE id = $8
RETURNING id, tag, name, description, asset_type_id, status_id, location_id, holder_member_id, purchase_date, retired_at, retired_reason, version, created_at, updated_at
`

type UpdateAssetParams struct {
	Name           string
	Description    string
	AssetTypeID    uuid.UUID
	StatusID       uuid.UUID
	LocationID     *uuid.UUID
	HolderMemberID *uuid.UUID
	PurchaseDate   pgtype.Date
	ID             uuid.UUID
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (InventoryAsset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.Name,
		arg.Description,
		arg.AssetTypeID,
		arg.StatusID,
		arg.LocationID,
		arg.HolderMemberID,
		arg.PurchaseDate,
		arg.ID,
	)
	var i InventoryAsset
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.AssetTypeID,
		&i.StatusID,
		&i.LocationID,
		&i.HolderMemberID,
		&i.PurchaseDate,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
