// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export_profiles.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createExportProfile = `-- name: CreateExportProfile :one
INSERT INTO inventory.export_profiles (id, owner_id, name, shared, layout)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at
`

type CreateExportProfileParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
	Shared  bool
	Layout  json.RawMessage
}

func (q *Queries) CreateExportProfile(ctx context.Context, arg CreateExportProfileParams) (InventoryExportProfile, error) {
	row := q.db.QueryRow(ctx, createExportProfile,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Shared,
		arg.Layout,
	)
	var i InventoryExportProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExportProfile = `-- name: DeleteExportProfile :execrows
UPDATE inventory.export_profiles SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Xoá mềm
func (q *Queries) DeleteExportProfile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExportProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExportProfile = `-- name: GetExportProfile :one
SELECT id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at FROM inventory.export_profiles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetExportProfile(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error) {
	row := q.db.QueryRow(ctx, getExportProfile, id)
	var i InventoryExportProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExportProfileAny = `-- name: GetExportProfileAny :one
SELECT id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at FROM inventory.export_profiles WHERE id = $1
`

// Kể cả profile đã xoá (khôi phục, kiểm tra quyền khôi phục)
func (q *Queries) GetExportProfileAny(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error) {
	row := q.db.QueryRow(ctx, getExportProfileAny, id)
	var i InventoryExportProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExportProfileAnyForUpdate = `-- name: GetExportProfileAnyForUpdate :one
SELECT id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at FROM inventory.export_profiles WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetExportProfileAnyForUpdate(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error) {
	row := q.db.QueryRow(ctx, getExportProfileAnyForUpdate, id)
	var i InventoryExportProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExportProfileForUpdate = `-- name: GetExportProfileForUpdate :one
SELECT id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at FROM inventory.export_profiles WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetExportProfileForUpdate(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error) {
	row := q.db.QueryRow(ctx, getExportProfileForUpdate, id)
	var i InventoryExportProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExportProfiles = `-- name: ListExportProfiles :many
SELECT id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at FROM inventory.export_profiles
WHERE (owner_id = $1 OR shared) AND deleted_at IS NULL
ORDER BY lower(name), id
`

// Của mình và mọi profile được chia sẻ
func (q *Queries) ListExportProfiles(ctx context.Context, ownerID uuid.UUID) ([]InventoryExportProfile, error) {
	rows, err := q.db.Query(ctx, listExportProfiles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryExportProfile{}
	for rows.Next() {
		var i InventoryExportProfile
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Shared,
			&i.Layout,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreExportProfile = `-- name: RestoreExportProfile :one
UPDATE inventory.export_profiles SET deleted_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreExportProfile(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error) {
	row := q.db.QueryRow(ctx, restoreExportProfile, id)
	var i InventoryExportProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateExportProfile = `-- name: UpdateExportProfile :one
UPDATE inventory.export_profiles
SET name = $1, shared = $2, layout = $3, version = version + 1, updated_at = now()
WHERE id = $4 AND version = $5 AND deleted_at IS NULL
RETURNING id, owner_id, name, shared, layout, version, created_at, updated_at, deleted_at
`

type UpdateExportProfileParams struct {
	Name    string
	Shared  bool
	Layout  json.RawMessage
	ID      uuid.UUID
	Version int32
}

// Optimistic locking: 0 hàng là version đã đổi
func (q *Queries) UpdateExportProfile(ctx context.Context, arg UpdateExportProfileParams) (InventoryExportProfile, error) {
	row := q.db.QueryRow(ctx, updateExportProfile,
		arg.Name,
		arg.Shared,
		arg.Layout,
		arg.ID,
		arg.Version,
	)
	var i InventoryExportProfile
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
