// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveStatus(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error)
	AttributeHasValues(ctx context.Context, attributeID uuid.UUID) (bool, error)
	// Chuyển cờ mặc định: bỏ cờ của kind trước, rồi đặt cho status mới (cùng tx)
	ClearDefaultStatus(ctx context.Context, kind string) error
	// Số tài sản chưa retire của mỗi loại, tách theo kind của status (sidebar, trang loại)
	CountActiveAssetsByTypeAndKind(ctx context.Context) ([]CountActiveAssetsByTypeAndKindRow, error)
	CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error)
	// Số tài sản (kể cả đã retire) đang dùng mỗi status
	CountAssetsByStatus(ctx context.Context) ([]CountAssetsByStatusRow, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (InventoryAsset, error)
	CreateAssetType(ctx context.Context, arg CreateAssetTypeParams) (InventoryAssetType, error)
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (InventoryAssetTypeAttribute, error)
	CreateExportProfile(ctx context.Context, arg CreateExportProfileParams) (InventoryExportProfile, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) (InventoryAssetAttributeOption, error)
	CreateStatus(ctx context.Context, arg CreateStatusParams) (InventoryAssetStatus, error)
	DeleteAssetValues(ctx context.Context, assetID uuid.UUID) error
	DeleteAttributeOptions(ctx context.Context, attributeID uuid.UUID) error
	// Xoá mềm
	DeleteExportProfile(ctx context.Context, id uuid.UUID) (int64, error)
	GetAsset(ctx context.Context, id uuid.UUID) (InventoryAsset, error)
	// NO KEY UPDATE: không chặn insert tham chiếu tài sản (giá trị thuộc tính, sau này là phiếu mượn)
	GetAssetForUpdate(ctx context.Context, id uuid.UUID) (InventoryAsset, error)
	GetAssetType(ctx context.Context, id uuid.UUID) (InventoryAssetType, error)
	GetAssetTypeForUpdate(ctx context.Context, id uuid.UUID) (InventoryAssetType, error)
	GetAttributeForUpdate(ctx context.Context, arg GetAttributeForUpdateParams) (InventoryAssetTypeAttribute, error)
	GetDefaultStatus(ctx context.Context, kind string) (InventoryAssetStatus, error)
	GetExportProfile(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error)
	// Kể cả profile đã xoá (khôi phục, kiểm tra quyền khôi phục)
	GetExportProfileAny(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error)
	GetExportProfileAnyForUpdate(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error)
	GetExportProfileForUpdate(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error)
	GetOptionForUpdate(ctx context.Context, arg GetOptionForUpdateParams) (InventoryAssetAttributeOption, error)
	GetStatus(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error)
	GetStatusForUpdate(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error)
	InsertAssetValue(ctx context.Context, arg InsertAssetValueParams) error
	// Nhãn thuộc tính đang dùng của mọi loại, theo thứ tự hiển thị (thẻ ở trang loại)
	ListActiveAttributeLabels(ctx context.Context) ([]ListActiveAttributeLabelsRow, error)
	// Khoá mọi status đang dùng khi đổi thứ tự
	ListActiveStatusesForUpdate(ctx context.Context) ([]InventoryAssetStatus, error)
	// Loại hệ thống (GENERAL) đứng đầu, rồi theo tên
	ListAssetTypes(ctx context.Context, includeArchived bool) ([]InventoryAssetType, error)
	// value_number đọc dạng text (giữ đúng số thập phân, không qua float); "" là không có số
	ListAssetValues(ctx context.Context, assetID uuid.UUID) ([]ListAssetValuesRow, error)
	// giá trị của thuộc tính để sắp (sort_attr NULL thì không khớp dòng nào)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error)
	// Mọi thuộc tính của loại, kể cả đã gỡ, theo thứ tự hiển thị
	ListAttributes(ctx context.Context, assetTypeID uuid.UUID) ([]InventoryAssetTypeAttribute, error)
	// Của mình và mọi profile được chia sẻ
	ListExportProfiles(ctx context.Context, ownerID uuid.UUID) ([]InventoryExportProfile, error)
	ListOptionsForType(ctx context.Context, assetTypeID uuid.UUID) ([]InventoryAssetAttributeOption, error)
	ListStatuses(ctx context.Context, includeArchived bool) ([]InventoryAssetStatus, error)
	// Giá trị của nhiều tài sản một lần (các dòng của một trang danh sách)
	ListValuesForAssets(ctx context.Context, assetIds []uuid.UUID) ([]ListValuesForAssetsRow, error)
	RemoveAttribute(ctx context.Context, arg RemoveAttributeParams) (int64, error)
	RemoveOption(ctx context.Context, arg RemoveOptionParams) (int64, error)
	RestoreAsset(ctx context.Context, arg RestoreAssetParams) (InventoryAsset, error)
	RestoreAttribute(ctx context.Context, arg RestoreAttributeParams) (InventoryAssetTypeAttribute, error)
	RestoreExportProfile(ctx context.Context, id uuid.UUID) (InventoryExportProfile, error)
	RestoreOption(ctx context.Context, arg RestoreOptionParams) (InventoryAssetAttributeOption, error)
	RestoreStatus(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error)
	RetireAsset(ctx context.Context, arg RetireAssetParams) (InventoryAsset, error)
	SetAssetTypeArchived(ctx context.Context, arg SetAssetTypeArchivedParams) (InventoryAssetType, error)
	// Sắp xếp lại (kéo thả): chỉ đổi vị trí
	SetAttributePosition(ctx context.Context, arg SetAttributePositionParams) error
	SetDefaultStatus(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error)
	SetOptionPosition(ctx context.Context, arg SetOptionPositionParams) error
	SetStatusPosition(ctx context.Context, arg SetStatusPositionParams) error
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (InventoryAsset, error)
	// Optimistic locking: 0 hàng là version đã đổi
	UpdateAssetType(ctx context.Context, arg UpdateAssetTypeParams) (InventoryAssetType, error)
	UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (InventoryAssetTypeAttribute, error)
	// Optimistic locking: 0 hàng là version đã đổi
	UpdateExportProfile(ctx context.Context, arg UpdateExportProfileParams) (InventoryExportProfile, error)
	UpdateOption(ctx context.Context, arg UpdateOptionParams) (InventoryAssetAttributeOption, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (InventoryAssetStatus, error)
}

var _ Querier = (*Queries)(nil)
