// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAssetType(ctx context.Context, id uuid.UUID) (InventoryAssetType, error)
}

var _ Querier = (*Queries)(nil)
