// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveStatus = `-- name: ArchiveStatus :one
UPDATE inventory.asset_statuses SET archived_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at
`

func (q *Queries) ArchiveStatus(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error) {
	row := q.db.QueryRow(ctx, archiveStatus, id)
	var i InventoryAssetStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsSystem,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearDefaultStatus = `-- name: ClearDefaultStatus :exec
UPDATE inventory.asset_statuses SET is_default = false, updated_at = now()
WHERE kind = $1 AND is_default
`

// Chuyển cờ mặc định: bỏ cờ của kind trước, rồi đặt cho status mới (cùng tx)
func (q *Queries) ClearDefaultStatus(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, clearDefaultStatus, kind)
	return err
}

const createStatus = `-- name: CreateStatus :one
INSERT INTO inventory.asset_statuses (id, name, kind, position)
VALUES ($1, $2, $3, $4)
RETURNING id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at
`

type CreateStatusParams struct {
	ID       uuid.UUID
	Name     string
	Kind     string
	Position int32
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (InventoryAssetStatus, error) {
	row := q.db.QueryRow(ctx, createStatus,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Position,
	)
	var i InventoryAssetStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsSystem,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultStatus = `-- name: GetDefaultStatus :one
SELECT id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at FROM inventory.asset_statuses WHERE kind = $1 AND is_default
`

func (q *Queries) GetDefaultStatus(ctx context.Context, kind string) (InventoryAssetStatus, error) {
	row := q.db.QueryRow(ctx, getDefaultStatus, kind)
	var i InventoryAssetStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsSystem,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatus = `-- name: GetStatus :one
SELECT id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at FROM inventory.asset_statuses WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error) {
	row := q.db.QueryRow(ctx, getStatus, id)
	var i InventoryAssetStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsSystem,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusForUpdate = `-- name: GetStatusForUpdate :one
SELECT id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at FROM inventory.asset_statuses WHERE id = $1 FOR NO KEY UPDATE
`

func (q *Queries) GetStatusForUpdate(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error) {
	row := q.db.QueryRow(ctx, getStatusForUpdate, id)
	var i InventoryAssetStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsSystem,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStatuses = `-- name: ListStatuses :many
SELECT id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at FROM inventory.asset_statuses
WHERE $1::boolean OR archived_at IS NULL
ORDER BY position, lower(name), id
`

func (q *Queries) ListStatuses(ctx context.Context, includeArchived bool) ([]InventoryAssetStatus, error) {
	rows, err := q.db.Query(ctx, listStatuses, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryAssetStatus{}
	for rows.Next() {
		var i InventoryAssetStatus
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.IsDefault,
			&i.IsSystem,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultStatus = `-- name: SetDefaultStatus :one
UPDATE inventory.asset_statuses SET is_default = true, updated_at = now()
WHERE id = $1
RETURNING id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at
`

func (q *Queries) SetDefaultStatus(ctx context.Context, id uuid.UUID) (InventoryAssetStatus, error) {
	row := q.db.QueryRow(ctx, setDefaultStatus, id)
	var i InventoryAssetStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsSystem,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE inventory.asset_statuses
SET name = $1, position = $2, updated_at = now()
WHERE id = $3
RETURNING id, name, kind, is_default, is_system, position, archived_at, created_at, updated_at
`

type UpdateStatusParams struct {
	Name     string
	Position int32
	ID       uuid.UUID
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (InventoryAssetStatus, error) {
	row := q.db.QueryRow(ctx, updateStatus, arg.Name, arg.Position, arg.ID)
	var i InventoryAssetStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsSystem,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
