// Package apicommon provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicommon

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// FieldError defines model for FieldError.
type FieldError struct {
	Detail string `json:"detail"`

	// Field Đường dẫn JSON của field, vd address.city
	Field string `json:"field"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// Paged defines model for Paged.
type Paged struct {
	Total int64 `json:"total"`
}

// Problem defines model for Problem.
type Problem struct {
	// Detail Giải thích cho lần xảy ra này
	Detail *string `json:"detail,omitempty"`

	// Errors Field sai, khi status là 422
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`

	// Title Câu ngắn, giống nhau mọi lần xảy ra
	Title string `json:"title"`

	// Type Định danh loại lỗi, ổn định, client so sánh bằng field này
	//
	// Example: /errors/asset-not-available
	Type string `json:"type"`
}

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"hFNNb9RIEP0rpdo9dmacj92Dr9kFwQEi5YgQ6rFr7AJ3t9PdjjJE/gUIiRwQJ6SEHHJACLjax4n4H/4n",
	"qO3MMMmMktO4p6tevffq9SkmRpVGk/YO41MspZWKPNn+dCAzCr+sMcajiuwMBWqpCGMsw51Al+SkZChK",
	"aSqrwmO8LVCxZlWp/tvPylDP2lNGFuta9LiH/PZe7FcuFGwc8E8kUMmTYcJOFD0wr16A9JoeMRXp/9Ya",
	"2+u1piTrmdwwwUsuwtcNiPOWdYa1wGloG2pcYrn0bALx6w+/fnTtZ51B2jVfNTw9fP4Mkq69ktB3CDhO",
	"QaapJedGCfsg8g52LdDSUcWWUoxf3AwSCy4vl/Vm8poSH7g8+S8QmRqrpMcYq4rTddjB5XRdpDdeFrcA",
	"WPt/93DFxWjj1lZZDiCbyB1YMylI3WfubQsfc9dcMvh8/i3JIckNFF1zpeGkay5nYCXo+flskz4KS3Tr",
	"gP2GwUkW8CZncF76ykExP4e9nR0UyJ5U3/a3pSnG+Nf4zxsY3yRlvBKTejlbWitn4TxgrgRl6ZNAz76g",
	"dVb78y8V6KxrvmsBGXftmc5A57IC1bXv+Y7oTXqHP9YT2LXvdA6p1DkUpmsuAlb7iQV07UcN12f9vYCk",
	"YNIenAE3v9A5TLrmp86GmC48phOpysAex4O7Y+kc+S1t/JY8llzISUEPRri/XRixNGs9LKGP9dT0Pg6u",
	"4b5RymhYPFiBx2TdoHR7FI2iYIQpScuSMcbdUTTaRYGl9HlYR13/DgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
