// Package apicommon provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicommon

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// FieldError defines model for FieldError.
type FieldError struct {
	Detail string `json:"detail"`

	// Field Đường dẫn JSON của field, vd address.city
	Field string `json:"field"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// Paged defines model for Paged.
type Paged struct {
	Total int64 `json:"total"`
}

// Problem defines model for Problem.
type Problem struct {
	// Detail Giải thích cho lần xảy ra này
	Detail *string `json:"detail,omitempty"`

	// Errors Field sai, khi status là 422
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`

	// Title Câu ngắn, giống nhau mọi lần xảy ra
	Title string `json:"title"`

	// Type Định danh loại lỗi, ổn định, client so sánh bằng field này
	//
	// Example: /errors/asset-not-available
	Type string `json:"type"`
}

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int
