// Package apicommon provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicommon

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// FieldError defines model for FieldError.
type FieldError struct {
	Detail string `json:"detail"`

	// Field Đường dẫn JSON của field, vd address.city
	Field string `json:"field"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// Paged defines model for Paged.
type Paged struct {
	Total int64 `json:"total"`
}

// Problem defines model for Problem.
type Problem struct {
	// Detail Giải thích cho lần xảy ra này
	Detail *string `json:"detail,omitempty"`

	// Errors Field sai, khi status là 422
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`

	// Title Câu ngắn, giống nhau mọi lần xảy ra
	Title string `json:"title"`

	// Type Định danh loại lỗi, ổn định, client so sánh bằng field này
	//
	// Example: /errors/asset-not-available
	Type string `json:"type"`
}

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"hFNPb9NOEP0qo/n9jtsk/QMHX8sfwQEq9YgQ2tgTe8C76+6uq4bKnwAh0QPihNTSQw8IAVf7mIrv4W+C",
	"1k5C2kRtLrG9M++9efP2FGOjCqNJe4fRKRbSSkWebPd2IFMK/6wxwqOS7BQFaqkIIyzCmUAXZ6RkKEpo",
	"IsvcY7QtUMkTVqXCaHsUfgIV6/kHgX5aBADWnlKyWFWiIzrk93eSvXGhYCPjg9EK5c69fNUCpBvyCVOe",
	"PLbW2M4Aawqynsn1DF5yHp7mIM5b1ilWAiehra9xseXCswnCrz/9+dU2X3UKSVt/1/D88OULiNvmSkLX",
	"IeA4AZkklpwbxOzDkLewK4GWjkq2lGD0ak4kFlpeL+vN+C3FPmh59igImRirpMcIy5KTddje5WR9SG+8",
	"zG8AsPYP93DFxdHGra2q7EE2iTuwZpyTusvcmxY+5ba+ZPDZ7EecQZwZyNv6SsNJW19OwUrQs/Pppvko",
	"LNGtA3YbBidZwLuMwXnpSwf57Bz2dnZQIHtSXdv/liYY4X/Df5diOE/KcCUm1ZJbWiun4b3HXAnK0ieB",
	"nn1O66r2Z99K0Glb/9QCUm6bM52CzmQJqm0+8q2hN83bf1hPYNt80BkkUmeQm7a+CFjNFxbQNp81XJ91",
	"5wLinEl7cAbc7EJnMG7r3zrtY7rwmE6kKoJ6HPbuDqVz5Le08VvyWHIuxzndG+HudGHE0qz1sIQ+1hPT",
	"+di7hvtGKaNhcWEFHpN1/aTbg9FgFIwwBWlZMEa4OxgNdlFgIX0W1lFVfwMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
